export type Category =
  | "Espacio"
  | "Tierra y clima"
  | "Física y química"
  | "Biología y salud"
  | "Ingeniería"
  | "Programación y robótica"
  | "Matemáticas y lógica"
  | "Simulacros y exámenes"
  | "Idiomas"
  | "Finanzas"
  | "Geografía e historia"
  | "Sociedad y ciudadanía"
  | "Arte y música"
  | "Educativos infantiles"
  | "Transporte"
  | "Emergencias"
  | "IA y datos"
  | "Ciberseguridad"
  | "Agricultura"
  | "Sostenibilidad"
  | "Emprendimiento"
  | "Psicología"
  | "Derecho"
  | "Comunicación"
  | "Oficios"
  | "Arquitectura"
  | "Juegos recreativos";

export type Access = "directo" | "opcional" | "mixto";

export type Simulator = {
  id: string;
  title: string;
  category: Category;
  description: string;
  href: string;
  tags: string[];
  access: Access;
};

export const categoryMeta: Record<Category, { glyph: string; description: string }> = {
  Espacio: { glyph: "◉", description: "Planetas, estrellas, órbitas y misiones" },
  "Tierra y clima": { glyph: "⌁", description: "Clima, geología, océanos y ambiente" },
  "Física y química": { glyph: "∿", description: "Fuerzas, materia, energía y laboratorios" },
  "Biología y salud": { glyph: "⌬", description: "Anatomía, células, genética y medicina" },
  Ingeniería: { glyph: "⚙", description: "Circuitos, electrónica y mecanismos" },
  "Programación y robótica": { glyph: "⌘", description: "Código, robots, algoritmos y seguridad" },
  "Matemáticas y lógica": { glyph: "∑", description: "Geometría, datos, cálculo y acertijos" },
  "Simulacros y exámenes": { glyph: "✓", description: "Pruebas académicas, idiomas y conducción" },
  Idiomas: { glyph: "A", description: "Vocabulario, gramática y comprensión" },
  Finanzas: { glyph: "↟", description: "Ahorro, inversión, presupuesto y economía" },
  "Geografía e historia": { glyph: "⌖", description: "Mapas, países, cultura e historia" },
  "Sociedad y ciudadanía": { glyph: "◎", description: "Gobierno, confianza y sistemas sociales" },
  "Arte y música": { glyph: "♪", description: "Dibujo, sonido, animación y creación 3D" },
  "Educativos infantiles": { glyph: "✦", description: "Aprendizaje seguro para niños y familias" },
  Transporte: { glyph: "↗", description: "Vuelo, conducción, barcos y navegación" },
  Emergencias: { glyph: "△", description: "Desastres, epidemias y gestión del riesgo" },
  "IA y datos": { glyph: "◫", description: "Inteligencia artificial, análisis y visualización de datos" },
  Ciberseguridad: { glyph: "⌾", description: "Privacidad, redes, criptografía y defensa digital" },
  Agricultura: { glyph: "♧", description: "Cultivos, suelos, riego y seguridad alimentaria" },
  Sostenibilidad: { glyph: "♻", description: "Clima, energía, recursos y economía circular" },
  Emprendimiento: { glyph: "↗", description: "Negocios, mercado, estrategia y gestión empresarial" },
  Psicología: { glyph: "Ψ", description: "Cognición, memoria, emociones y conducta" },
  Derecho: { glyph: "⚖", description: "Justicia, ciudadanía, leyes y argumentación" },
  Comunicación: { glyph: "◌", description: "Expresión, periodismo, medios y alfabetización digital" },
  Oficios: { glyph: "⌑", description: "Electricidad, mecánica, construcción y seguridad laboral" },
  Arquitectura: { glyph: "▱", description: "Planos, espacios, estructuras y urbanismo" },
  "Juegos recreativos": { glyph: "◇", description: "Estrategia, cartas, puzles y aventuras" },
};

const slug = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const r = (
  title: string,
  category: Category,
  description: string,
  href: string,
  tags: string[],
  access: Access = "directo",
): Simulator => ({
  id: `${slug(category)}-${slug(title)}`,
  title,
  category,
  description,
  href,
  tags,
  access,
});

export const simulators: Simulator[] = [
  // Espacio y astronomía
  r("NASA Eyes: Sistema Solar", "Espacio", "Explora planetas, lunas, asteroides y misiones en un entorno 3D.", "https://eyes.nasa.gov/apps/solar-system/", ["NASA", "3D"]),
  r("NASA Eyes: Exoplanetas", "Espacio", "Viaja por miles de mundos descubiertos fuera del sistema solar.", "https://eyes.nasa.gov/apps/exo/", ["Exoplanetas", "Datos"]),
  r("NASA Eyes: Asteroides", "Espacio", "Observa órbitas y aproximaciones de objetos cercanos a la Tierra.", "https://eyes.nasa.gov/apps/asteroids/", ["Órbitas", "NASA"]),
  r("Experience Curiosity", "Espacio", "Conduce el rover Curiosity y utiliza sus instrumentos sobre Marte.", "https://eyes.nasa.gov/apps/curiosity/", ["Marte", "Rover"]),
  r("NASA Solar System Exploration", "Espacio", "Guías, visualizaciones y datos de los cuerpos del sistema solar.", "https://science.nasa.gov/solar-system/", ["NASA", "Ciencia"]),
  r("Stellarium Web", "Espacio", "Planetario que reproduce el cielo desde cualquier lugar y fecha.", "https://stellarium-web.org/", ["Planetario", "Cielo"]),
  r("Solar System Scope", "Espacio", "Modelo orbital navegable con constelaciones y escalas planetarias.", "https://www.solarsystemscope.com/", ["Órbitas", "3D"]),
  r("NASA Mars Trek", "Espacio", "Recorre Marte con mapas, mediciones y datos de misiones.", "https://trek.nasa.gov/mars/", ["Marte", "Mapas"]),
  r("NASA Moon Trek", "Espacio", "Explora la superficie lunar y sus accidentes geográficos.", "https://trek.nasa.gov/moon/", ["Luna", "Mapas"]),
  r("ViewSpace", "Espacio", "Interactivos y videos científicos sobre astronomía y ciencias de la Tierra.", "https://viewspace.org/", ["Astronomía", "Educativo"]),
  r("Earth Space Lab", "Espacio", "Rotación terrestre, estaciones, sombras, órbitas y coordenadas en 3D.", "https://www.earthspacelab.com/", ["Tierra", "Órbitas"]),
  r("WorldWide Telescope", "Espacio", "Explorador web de datos astronómicos, imágenes y recorridos.", "https://worldwidetelescope.org/home", ["Telescopio", "Datos"]),
  r("100,000 Stars", "Espacio", "Viaje WebGL desde el Sol hasta la estructura de la Vía Láctea.", "https://stars.chromeexperiments.com/", ["WebGL", "Estrellas"]),
  r("Asterank 3D", "Espacio", "Miles de asteroides representados en una escena orbital 3D.", "https://www.asterank.com/3d/", ["Asteroides", "Datos"]),
  r("NASA Space Place", "Espacio", "Juegos y actividades de astronomía para público infantil.", "https://spaceplace.nasa.gov/menu/play/", ["NASA", "Niños"]),

  // Tierra, clima y ambiente
  r("earth.nullschool", "Tierra y clima", "Vientos, océanos, temperatura y contaminantes sobre un globo vivo.", "https://earth.nullschool.net/", ["Clima", "Datos en vivo"]),
  r("Windy", "Tierra y clima", "Compara modelos meteorológicos, lluvia, viento, oleaje y temperatura.", "https://www.windy.com/", ["Pronóstico", "Mapas"]),
  r("Ventusky", "Tierra y clima", "Mapas animados de clima, viento, tormentas y calidad del aire.", "https://www.ventusky.com/", ["Clima", "Animación"]),
  r("Zoom Earth", "Tierra y clima", "Sigue nubes, huracanes, incendios y precipitaciones casi en directo.", "https://zoom.earth/", ["Satélite", "En vivo"]),
  r("NASA Worldview", "Tierra y clima", "Compara capas satelitales y fenómenos ambientales globales.", "https://worldview.earthdata.nasa.gov/", ["NASA", "Satélite"]),
  r("En-ROADS", "Sostenibilidad", "Cambia políticas y observa sus efectos climáticos hasta 2100.", "https://www.climateinteractive.org/en-roads/", ["Clima", "Política"]),
  r("C-ROADS", "Sostenibilidad", "Prueba compromisos de emisiones por regiones y países.", "https://www.climateinteractive.org/c-roads", ["Emisiones", "Sistemas"]),
  r("NASA Climate Interactives", "Tierra y clima", "Colección de visualizaciones sobre clima, hielo, carbono y océanos.", "https://climate.nasa.gov/interactives/", ["NASA", "Clima"]),
  r("Global Forest Watch", "Tierra y clima", "Observa deforestación, incendios y cambios de cobertura forestal.", "https://www.globalforestwatch.org/map/", ["Bosques", "Satélite"]),
  r("USGS Earthquake Map", "Tierra y clima", "Terremotos mundiales por magnitud, profundidad y fecha.", "https://earthquake.usgs.gov/earthquakes/map/", ["Sismos", "En vivo"]),
  r("Visible Geology", "Tierra y clima", "Modelado 3D de estratos, fallas, intrusiones y topografía.", "https://www.visiblegeology.com/", ["Geología", "3D"]),
  r("Orb.Farm", "Tierra y clima", "Crea un ecosistema acuático con plantas, peces y microorganismos.", "https://orb.farm/", ["Ecosistema", "Sandbox"]),
  r("Survive the Century", "Sostenibilidad", "Historia interactiva de decisiones climáticas y futuros posibles.", "https://survivethecentury.net/", ["Clima", "Narrativo"]),

  // Física y química
  r("PhET Interactive Simulations", "Física y química", "Simulaciones de física, química, biología, Tierra y matemáticas.", "https://phet.colorado.edu/es/", ["Laboratorio", "Español"]),
  r("Walter Fendt", "Física y química", "Applets HTML5 de mecánica, óptica, electricidad y ondas.", "https://www.walter-fendt.de/html5/phes/", ["Física", "HTML5"]),
  r("oPhysics", "Física y química", "Simulaciones de movimiento, fuerzas, electricidad, ondas y óptica.", "https://ophysics.com/", ["Física", "Laboratorio"]),
  r("myPhysicsLab", "Física y química", "Modelos manipulables de péndulos, colisiones, resortes y caos.", "https://www.myphysicslab.com/", ["Mecánica", "Caos"]),
  r("Falstad Math & Physics", "Física y química", "Simulaciones interactivas de ondas, campos y mecánica cuántica.", "https://www.falstad.com/mathphysics.html", ["Campos", "Ondas"]),
  r("The Physics Aviary", "Física y química", "Laboratorios de movimiento, electricidad, óptica y energía.", "https://www.thephysicsaviary.com/Physics/Programs/Labs/find.php", ["Laboratorios", "Física"]),
  r("Physics Classroom Interactives", "Física y química", "Actividades HTML5 de mecánica, electricidad, ondas y química.", "https://www.physicsclassroom.com/interactive", ["HTML5", "Secundaria"]),
  r("LearnChemE Virtual Laboratories", "Física y química", "Reactores, catálisis, transferencia de calor y procesos químicos.", "https://learncheme.com/virtual-laboratories/", ["Química", "Ingeniería"]),
  r("LearnChemE Simulations", "Física y química", "Más de 290 simulaciones; algunas funcionan en web y otras se descargan.", "https://learncheme.com/simulations/", ["Procesos", "Universidad"], "mixto"),
  r("JavaLab", "Física y química", "Cientos de simulaciones de física, química, astronomía y biología.", "https://javalab.org/en/", ["Ciencia", "HTML5"]),
  r("NetLogo Web", "Física y química", "Modelos de difusión, reacciones, poblaciones y sistemas complejos.", "https://www.netlogoweb.org/launch", ["Agentes", "Modelos"]),
  r("Andrew Duffy Physics Sims", "Física y química", "Más de 200 simulaciones universitarias ejecutables en el navegador.", "https://physics.bu.edu/~duffy/sims.html", ["Universidad", "Física"]),
  r("3JCN Physics Simulations", "Física y química", "Amplia colección abierta de simulaciones de física.", "https://www.new3jcn.com/simulation.html", ["Física", "Colección"]),
  r("CK-12 Physics Simulations", "Física y química", "Experiencias de física aplicadas a situaciones reales.", "https://interactives.ck12.org/simulations/physics.html", ["Física", "Escuela"], "opcional"),
  r("ChemCollective", "Física y química", "Laboratorios virtuales, escenarios y actividades de química.", "https://chemcollective.org/", ["Química", "Laboratorio"]),
  r("Open Source Physics", "Física y química", "Biblioteca de modelos y recursos abiertos para enseñar física.", "https://www.compadre.org/osp/", ["Código abierto", "Física"], "mixto"),
  r("WebGL Fluid Simulation", "Física y química", "Crea fluidos digitales que reaccionan a cada movimiento.", "https://paveldogreat.github.io/WebGL-Fluid-Simulation/", ["Fluidos", "WebGL"]),
  r("Sandspiel", "Física y química", "Combina arena, agua, fuego, hielo y vida en un mundo emergente.", "https://sandspiel.club/", ["Partículas", "Creativo"]),
  r("SciChamp", "Física y química", "Juegos de física, química y biología para secundaria.", "https://scichamp.com/", ["Juegos", "Secundaria"]),
  r("The Science Playground", "Física y química", "Directorio de simulaciones y juegos científicos gratuitos en la web.", "https://thescienceplayground.com/index.php/free-web-links/", ["Directorio", "Ciencia"]),

  // Biología y salud
  r("MolView", "Biología y salud", "Construye moléculas y examina su geometría tridimensional.", "https://molview.org/", ["Moléculas", "3D"]),
  r("LabXchange", "Biología y salud", "Laboratorios, secuencias y recursos científicos de Harvard.", "https://www.labxchange.org/library", ["Laboratorios", "Harvard"], "opcional"),
  r("HHMI BioInteractive", "Biología y salud", "Animaciones, laboratorios y recursos de biología basados en evidencia.", "https://www.biointeractive.org/", ["Biología", "Ciencia"]),
  r("Learn.Genetics", "Biología y salud", "Genética, ADN, células y herencia mediante interactivos.", "https://learn.genetics.utah.edu/", ["Genética", "ADN"]),
  r("BioMan Biology", "Biología y salud", "Juegos de células, genética, ecología y fisiología.", "https://biomanbio.com/", ["Biología", "Juegos"]),
  r("Ask A Biologist", "Biología y salud", "Juegos y simulaciones sobre células, evolución y anatomía.", "https://askabiologist.asu.edu/games-and-simulations", ["Biología", "ASU"]),
  r("Cells Alive", "Biología y salud", "Células, mitosis, microorganismos e inmunología interactiva.", "https://www.cellsalive.com/", ["Células", "Microscopía"]),
  r("NC BioNetwork Virtual Microscope", "Biología y salud", "Practica el manejo de un microscopio y observa muestras.", "https://elearning.ncbionetwork.org/virtuallab/microscope/", ["Microscopio", "Laboratorio"]),
  r("Virtual Microscope", "Biología y salud", "Muestras digitalizadas para aprender microscopía y anatomía.", "https://virtualmicroscope.org/", ["Microscopía", "Muestras"]),
  r("NMSU Virtual Labs", "Biología y salud", "Laboratorios virtuales de microbiología, alimentos y ciencias.", "https://virtuallabs.nmsu.edu/", ["Laboratorios", "Universidad"]),
  r("Innerbody", "Biología y salud", "Mapas y explicaciones interactivas del cuerpo humano.", "https://www.innerbody.com/htm/body.html", ["Anatomía", "Cuerpo"]),
  r("GetBodySmart", "Biología y salud", "Diagramas y cuestionarios de anatomía y fisiología.", "https://www.getbodysmart.com/", ["Anatomía", "Cuestionarios"]),
  r("RCSB Mol* Viewer", "Biología y salud", "Explora proteínas, ADN y estructuras experimentales complejas.", "https://www.rcsb.org/3d-view", ["Proteínas", "3D"]),
  r("BioDigital Human", "Biología y salud", "Recorre anatomía, enfermedades y tratamientos en un cuerpo 3D.", "https://human.biodigital.com/", ["Anatomía", "3D"], "mixto"),
  r("HHMI EarthViewer", "Biología y salud", "Viaja por 4.500 millones de años de evolución planetaria.", "https://media.hhmi.org/biointeractive/earthviewer_web/", ["Evolución", "Tiempo"]),
  r("Virus Explorer", "Biología y salud", "Compara estructuras, genomas y mecanismos de distintos virus.", "https://media.hhmi.org/biointeractive/embed/virus-explorer-embed/index.html", ["Virus", "3D"]),
  r("Modeling Disease Spread", "Biología y salud", "Experimenta con contagio, inmunidad y propagación epidémica.", "https://media.hhmi.org/biointeractive/click/modeling-disease-spread/index.html", ["Epidemias", "Modelo"]),
  r("Nobel Blood Typing Game", "Biología y salud", "Identifica grupos sanguíneos y practica transfusiones seguras.", "https://educationalgames.nobelprize.org/educational/medicine/bloodtypinggame/", ["Sangre", "Medicina"]),
  r("Human Bio Media Blood Lab", "Biología y salud", "Laboratorio virtual de tipificación sanguínea.", "https://www.humanbiomedia.org/blood-typing-lab-simulation/", ["Sangre", "Laboratorio"]),
  r("AnatomyTOOL", "Biología y salud", "Modelos 3D, juegos y cuestionarios anatómicos.", "https://anatomytool.org/interactive", ["Anatomía", "3D"]),
  r("Free Anatomy Quiz", "Biología y salud", "Más de 200 pruebas de anatomía, fisiología y patología.", "https://www.free-anatomy-quiz.com/", ["Anatomía", "Quiz"]),
  r("The Human Body Game", "Biología y salud", "Sistemas, órganos y huesos del cuerpo humano para primaria.", "https://www.thehumanbodygame.co.uk/", ["Cuerpo", "Niños"]),
  r("Eterna", "Biología y salud", "Resuelve plegamientos de ARN y participa en ciencia ciudadana.", "https://eternagame.org/", ["ARN", "Ciencia"], "opcional"),

  // Ingeniería y electrónica
  r("Falstad Circuit Simulator", "Ingeniería", "Construye circuitos y observa la corriente en tiempo real.", "https://www.falstad.com/circuit/circuitjs.html", ["Circuitos", "Electricidad"]),
  r("CircuitVerse", "Ingeniería", "Diseña sistemas lógicos digitales y observa su comportamiento.", "https://circuitverse.org/simulator", ["Lógica", "Circuitos"], "opcional"),
  r("Wokwi", "Ingeniería", "Programa Arduino, ESP32, sensores y pantallas sin hardware físico.", "https://wokwi.com/", ["Arduino", "Electrónica"], "opcional"),
  r("MechSimulator", "Ingeniería", "Construye y analiza mecanismos, eslabones y movimientos.", "https://www.mechsimulator.com/", ["Mecánica", "Mecanismos"]),
  r("MakeCode micro:bit", "Ingeniería", "Simula micro:bit con bloques o JavaScript antes de usar hardware.", "https://makecode.microbit.org/", ["micro:bit", "Bloques"], "opcional"),

  // Programación, robótica y ciberseguridad
  r("MakeCode Arcade", "Programación y robótica", "Crea videojuegos retro con bloques o JavaScript.", "https://arcade.makecode.com/", ["Videojuegos", "Código"], "opcional"),
  r("VEXcode VR", "Programación y robótica", "Programa un robot virtual en escenarios y desafíos 3D.", "https://vr.vex.com/", ["Robótica", "Bloques"], "opcional"),
  r("Blockly Games", "Programación y robótica", "Juegos progresivos para aprender conceptos de programación.", "https://blockly.games/", ["Bloques", "Principiantes"]),
  r("Code.org Game Lab", "Programación y robótica", "Diseña juegos y animaciones con JavaScript visual.", "https://code.org/educate/gamelab", ["Juegos", "JavaScript"], "opcional"),
  r("Scratch", "Programación y robótica", "Crea historias, animaciones y videojuegos con bloques.", "https://scratch.mit.edu/projects/editor/", ["MIT", "Bloques"], "opcional"),
  r("Snap!", "Programación y robótica", "Lenguaje visual avanzado inspirado en Scratch.", "https://snap.berkeley.edu/snap/snap.html", ["Berkeley", "Bloques"]),
  r("Turtle Academy", "Programación y robótica", "Aprende Logo guiando una tortuga en el navegador.", "https://turtleacademy.com/", ["Logo", "Principiantes"]),
  r("Flexbox Froggy", "Programación y robótica", "Aprende CSS Flexbox ayudando a unas ranas.", "https://flexboxfroggy.com/#es", ["CSS", "Juego"]),
  r("Grid Garden", "Programación y robótica", "Practica CSS Grid cultivando un jardín.", "https://cssgridgarden.com/#es", ["CSS", "Juego"]),
  r("CSS Diner", "Programación y robótica", "Aprende selectores CSS mediante desafíos visuales.", "https://flukeout.github.io/", ["CSS", "Selectores"]),
  r("RoboBlockly", "Programación y robótica", "Programación de robots y matemáticas con bloques.", "https://roboblockly.org/", ["Robótica", "STEM"]),
  r("Rocksi", "Programación y robótica", "Brazo robótico 3D con programación Blockly y sin registro.", "https://rocksi.net/", ["Robot", "3D"]),
  r("FTC SIM", "Programación y robótica", "Robots FIRST con bloques o Java en campos virtuales.", "https://ftcsim.org/", ["FIRST", "Robótica"], "opcional"),
  r("Virtual Robot Simulator", "Programación y robótica", "Programa robots FTC con Blockly o Java.", "https://powerplay.vrobotsim.online/", ["FTC", "Robot"]),
  r("Open Roberta Lab", "Programación y robótica", "Programa robots virtuales con bloques NEPO.", "https://lab.open-roberta.org/", ["NEPO", "Robot"], "opcional"),
  r("Robot Benchmark", "Programación y robótica", "Retos de programación y control de robots virtuales.", "https://robotbenchmark.net/", ["Webots", "Retos"], "opcional"),
  r("Elevator Saga", "Programación y robótica", "Programa ascensores eficientes mediante JavaScript.", "https://play.elevatorsaga.com/", ["JavaScript", "Juego"]),
  r("SQLBolt", "Programación y robótica", "Lecciones y ejercicios interactivos de SQL.", "https://sqlbolt.com/", ["SQL", "Base de datos"]),
  r("SQL Murder Mystery", "Programación y robótica", "Resuelve un asesinato consultando una base SQLite.", "https://mystery.knightlab.com/", ["SQL", "Misterio"]),
  r("Learn Git Branching", "Programación y robótica", "Simulador visual de ramas, commits y fusiones en español.", "https://learngitbranching.js.org/?locale=es_ES", ["Git", "Visual"]),
  r("Regex Crossword", "Programación y robótica", "Crucigramas resueltos con expresiones regulares.", "https://regexcrossword.com/", ["Regex", "Puzle"]),
  r("GitMastery", "Programación y robótica", "Juego interactivo para practicar comandos de Git.", "https://gitmastery.me/", ["Git", "Juego"]),
  r("VisuAlgo", "Programación y robótica", "Visualizaciones manipulables de algoritmos y estructuras de datos.", "https://visualgo.net/", ["Algoritmos", "Datos"]),
  r("Python Tutor", "Programación y robótica", "Ejecuta código paso a paso y muestra variables, objetos y memoria.", "https://pythontutor.com/", ["Python", "Visualizador"]),
  r("CS Field Guide Interactives", "Programación y robótica", "Compresión, criptografía, autómatas, algoritmos y redes.", "https://www.csfieldguide.org.nz/en/interactives/", ["Informática", "Interactivos"]),
  r("EarSketch", "Programación y robótica", "Aprende Python o JavaScript produciendo música.", "https://earsketch.gatech.edu/", ["Código", "Música"]),
  r("Interland", "Programación y robótica", "Cuatro juegos de ciudadanía y seguridad digital.", "https://beinternetawesome.withgoogle.com/interland/", ["Ciberseguridad", "Niños"]),
  r("NOVA Cybersecurity Lab", "Ciberseguridad", "Defiende sistemas y aprende sobre contraseñas, código y ataques.", "https://www.pbslearningmedia.org/resource/nvcy-sci-cyberlab/nova-cybersecurity-lab/", ["Ciberseguridad", "Simulacro"], "opcional"),
  r("TensorFlow Playground", "IA y datos", "Entrena una red neuronal y observa sus fronteras de decisión.", "https://playground.tensorflow.org/", ["IA", "Machine learning"]),
  r("Teachable Machine", "Programación y robótica", "Crea un modelo de IA con imágenes, sonidos o movimientos.", "https://teachablemachine.withgoogle.com/", ["IA", "Cámara"]),
  r("Algorithm Visualizer", "Programación y robótica", "Sigue la ejecución animada de algoritmos y estructuras.", "https://algorithm-visualizer.org/", ["Algoritmos", "Animación"]),

  // Matemáticas, datos y lógica
  r("Desmos", "Matemáticas y lógica", "Calculadoras gráficas, geometría y visualización 3D.", "https://www.desmos.com/calculator?lang=es", ["Gráficas", "Álgebra"]),
  r("Desmos 3D", "Matemáticas y lógica", "Grafica ecuaciones tridimensionales y anímalas con parámetros.", "https://www.desmos.com/3d", ["3D", "Funciones"]),
  r("GeoGebra", "Matemáticas y lógica", "Geometría, álgebra, estadística, cálculo y recursos interactivos.", "https://www.geogebra.org/?lang=es", ["Geometría", "Álgebra"]),
  r("Polypad", "Matemáticas y lógica", "Manipulativos digitales para números, geometría, álgebra y probabilidad.", "https://polypad.amplify.com/", ["Manipulativos", "Aula"]),
  r("CODAP", "Matemáticas y lógica", "Analiza datos, crea gráficos y explora modelos estadísticos.", "https://codap.concord.org/app/", ["Datos", "Estadística"]),
  r("Math Playground", "Matemáticas y lógica", "Juegos de aritmética, lógica, geometría y resolución de problemas.", "https://www.mathplayground.com/", ["Juegos", "Primaria"]),
  r("Math Is Fun", "Matemáticas y lógica", "Explicaciones, ejercicios, puzles y herramientas matemáticas.", "https://www.mathsisfun.com/", ["Matemáticas", "Puzles"]),
  r("Transum", "Matemáticas y lógica", "Actividades y juegos matemáticos para distintas edades.", "https://www.transum.org/Software/", ["Juegos", "Aula"]),
  r("NRICH", "Matemáticas y lógica", "Problemas abiertos, retos y exploraciones matemáticas.", "https://nrich.maths.org/", ["Problemas", "Razonamiento"]),
  r("RoomRecess Math", "Matemáticas y lógica", "Juegos matemáticos gratuitos para primaria.", "https://www.roomrecess.com/pages/MathGames.html", ["Primaria", "Juegos"]),
  r("Math Learning Center Apps", "Matemáticas y lógica", "Regletas, fracciones, geoplano, recta numérica y marcos.", "https://www.mathlearningcenter.org/apps", ["Manipulativos", "Aula"]),
  r("Didax Virtual Manipulatives", "Matemáticas y lógica", "Bloques, fichas, números y fracciones manipulables.", "https://www.didax.com/math/virtual-manipulatives.html", ["Manipulativos", "Primaria"]),
  r("Visnos Math Demos", "Matemáticas y lógica", "Ángulos, polígonos, relojes, porcentajes y tablas.", "https://www.visnos.com/demos", ["Geometría", "Visual"]),
  r("MathsBot Manipulatives", "Matemáticas y lógica", "Mosaicos algebraicos, tangram, dados, dominó y geoplano.", "https://mathsbot.com/manipulativeMenu", ["Manipulativos", "Álgebra"]),
  r("Shodor Interactivate", "Matemáticas y lógica", "Probabilidad, funciones, geometría y modelación.", "https://www.shodor.org/interactivate/activities/", ["Modelos", "Estadística"]),
  r("Seeing Theory", "Matemáticas y lógica", "Probabilidad y estadística mediante visualizaciones interactivas.", "https://seeing-theory.brown.edu/", ["Estadística", "Visual"]),
  r("Euclidea", "Matemáticas y lógica", "Retos de construcciones geométricas con regla y compás.", "https://www.euclidea.xyz/", ["Geometría", "Retos"]),
  r("SageMathCell", "Matemáticas y lógica", "Cálculo, álgebra, gráficas y programación matemática.", "https://sagecell.sagemath.org/", ["Cálculo", "Álgebra"]),
  r("Mathics Live", "Matemáticas y lógica", "Sistema de álgebra computacional de código abierto.", "https://mathics.org/", ["Cálculo", "CAS"]),
  r("Gapminder Tools", "Matemáticas y lógica", "Explora indicadores mundiales mediante gráficos animados.", "https://www.gapminder.org/tools/", ["Datos", "Mundo"]),
  r("Mathler", "Matemáticas y lógica", "Acertijos aritméticos diarios y modo práctica ilimitado.", "https://www.mathler.com/", ["Aritmética", "Diario"]),
  r("Nerdle", "Matemáticas y lógica", "Encuentra una operación matemática oculta usando pistas.", "https://nerdlegame.com/", ["Cálculo", "Diario"], "opcional"),
  r("Clues by Sam", "Matemáticas y lógica", "Deducción lógica diaria sin posibilidad de adivinar.", "https://cluesbysam.com/", ["Lógica", "Misterio"]),
  r("Mystery-o-Matic", "Matemáticas y lógica", "Misterio lógico generado diariamente.", "https://mystery-o-matic.com/en", ["Deducción", "Diario"]),
  r("Murdle", "Matemáticas y lógica", "Misterios diarios con sospechoso, lugar y arma.", "https://murdle.com/", ["Lógica", "Misterio"]),
  r("SineRider", "Matemáticas y lógica", "Resuelve niveles dibujando funciones matemáticas.", "https://sinerider.com/", ["Funciones", "Juego"]),
  r("2048", "Matemáticas y lógica", "Combina números y planifica movimientos en el clásico puzle.", "https://play2048.co/", ["Números", "Puzle"]),
  r("Hextris", "Matemáticas y lógica", "Puzle de rotación y patrones alrededor de un hexágono.", "https://hextris.io/", ["Lógica", "Puzle"]),
  r("Sudoku.game", "Matemáticas y lógica", "Sudokus gratuitos con distintos niveles de dificultad.", "https://sudoku.game/", ["Sudoku", "Lógica"]),

  // Simulacros y exámenes
  r("ICFES Saber 11", "Simulacros y exámenes", "Información, guías y materiales oficiales para Saber 11.", "https://www.icfes.gov.co/evaluaciones-icfes/saber-11/", ["ICFES", "Colombia"]),
  r("ICFES Saber Pro y TyT", "Simulacros y exámenes", "Guías y materiales oficiales de educación superior.", "https://www.icfes.gov.co/evaluaciones-icfes/", ["ICFES", "Universidad"]),
  r("Cambridge Test Your English", "Simulacros y exámenes", "Prueba breve para estimar el nivel de inglés.", "https://www.cambridgeenglish.org/test-your-english/", ["Inglés", "Cambridge"]),
  r("Test-English", "Simulacros y exámenes", "Práctica de gramática, lectura, escucha y exámenes por nivel.", "https://test-english.com/", ["Inglés", "CEFR"]),
  r("Exam English", "Simulacros y exámenes", "Pruebas de nivel y práctica para exámenes internacionales.", "https://www.examenglish.com/", ["Inglés", "Exámenes"]),
  r("IELTS Practice", "Simulacros y exámenes", "Materiales oficiales y pruebas de práctica IELTS.", "https://ielts.org/take-a-test/preparation-resources", ["IELTS", "Inglés"]),
  r("British Council IELTS", "Simulacros y exámenes", "Práctica de escucha, lectura, escritura y conversación.", "https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests", ["IELTS", "British Council"]),
  r("TOEFL TestReady", "Simulacros y exámenes", "Recursos y práctica oficial para TOEFL.", "https://www.ets.org/toefl/test-takers/ibt/prepare/toefl-testready.html", ["TOEFL", "ETS"], "opcional"),
  r("ACT Free Test Prep", "Simulacros y exámenes", "Preguntas, exámenes y recursos oficiales gratuitos.", "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep.html", ["ACT", "Universidad"]),
  r("4Tests", "Simulacros y exámenes", "Pruebas gratuitas de educación, empleo y certificaciones.", "https://www.4tests.com/", ["Pruebas", "Práctica"]),
  r("Driving-Tests.org", "Simulacros y exámenes", "Práctica de conducción y señales por estados de EE. UU.", "https://driving-tests.org/", ["Conducción", "Licencia"]),
  r("California DMV Sample Tests", "Simulacros y exámenes", "Exámenes públicos de conocimientos para conducir.", "https://www.dmv.ca.gov/portal/driver-education-and-safety/educational-materials/sample-driver-license-dl-knowledge-tests/", ["Conducción", "DMV"]),
  r("Monkeytype", "Simulacros y exámenes", "Pruebas configurables de velocidad y precisión al escribir.", "https://monkeytype.com/", ["Mecanografía", "Velocidad"], "opcional"),
  r("Keybr", "Simulacros y exámenes", "Entrenamiento adaptativo de mecanografía.", "https://www.keybr.com/", ["Mecanografía", "Práctica"], "opcional"),
  r("10FastFingers", "Simulacros y exámenes", "Pruebas rápidas de escritura en varios idiomas.", "https://10fastfingers.com/typing-test/spanish", ["Mecanografía", "Español"], "opcional"),
  r("HiSET Official Practice", "Simulacros y exámenes", "Lectura, escritura, matemáticas, ciencias y sociales en inglés y español.", "https://hiset.org/prepare-for-your-test/practice-tests/", ["HiSET", "Oficial"]),
  r("GED Test Previews", "Simulacros y exámenes", "Muestras oficiales de los cuatro componentes del GED.", "https://www.ged.com/en/test-previews.html", ["GED", "Oficial"]),
  r("MTEL Practice Tests", "Simulacros y exámenes", "Simulacros gratuitos para numerosas áreas docentes.", "https://www.mtel.nesinc.com/PageView.aspx?f=HTML_FRAG%2FGENRB_MTELPractice.html", ["Docentes", "Pruebas"]),
  r("Ohio State Practice Tests", "Simulacros y exámenes", "Lengua, matemáticas, ciencias y sociales.", "https://education.ohio.gov/Topics/Testing/Ohios-State-Test-in-ELA-Math-Science-SocialStudies/Sample-test-items-and-practice-tests", ["Escuela", "TestNav"]),
  r("ISASP TestNav Practice", "Simulacros y exámenes", "Práctica pública dentro del entorno TestNav.", "https://ia.mypearsonsupport.com/test-prep/", ["TestNav", "Escuela"]),
  r("TOEIC Official Samples", "Simulacros y exámenes", "Cuadernillos oficiales de comprensión, habla y escritura.", "https://www.ets.org/toeic/test-takers/prepare.html", ["TOEIC", "ETS"]),
  r("DELE Sample Exams", "Simulacros y exámenes", "Modelos oficiales con PDF y audios de todos los niveles.", "https://albuquerque.cervantes.es/en/diplomas_spanish/model_exam.htm", ["DELE", "Español"]),
  r("TCF Simulator TV5MONDE", "Simulacros y exámenes", "Banco de 600 preguntas y simulación de 80 preguntas.", "https://apprendre.tv5monde.com/en/tcf", ["Francés", "TCF"]),
  r("Preply English Test", "Simulacros y exámenes", "36 preguntas, resultado inmediato y sin registro.", "https://preply.com/en/language-tests/english", ["Inglés", "Nivel"]),
  r("Strømmen English Test", "Simulacros y exámenes", "Nivel CEFR sin correo ni cuenta.", "https://strommeninc.com/language-tests/english-level-test/", ["Inglés", "CEFR"]),
  r("EnglishRadar", "Simulacros y exámenes", "60 preguntas desde A1 hasta C2 con resultado inmediato.", "https://www.englishradar.com/english-test/", ["Inglés", "CEFR"]),
  r("Oxford Online English Tests", "Simulacros y exámenes", "Lectura, escucha, gramática y vocabulario.", "https://www.oxfordonlineenglish.com/english-level-test", ["Inglés", "Nivel"]),
  r("Mometrix SAT Math", "Simulacros y exámenes", "Simulacro gratuito de matemáticas para el SAT.", "https://www.mometrix.com/academy/sat-math-practice-test/", ["SAT", "Matemáticas"]),

  // Idiomas
  r("Games to Learn English", "Idiomas", "Juegos de vocabulario, gramática, escucha y conversación.", "https://www.gamestolearnenglish.com/", ["Inglés", "Juegos"]),
  r("Digital Dialects", "Idiomas", "Juegos gratuitos para aprender decenas de idiomas.", "https://www.digitaldialects.com/", ["Vocabulario", "Idiomas"]),
  r("British Council LearnEnglish Kids", "Idiomas", "Juegos, historias y canciones para aprender inglés.", "https://learnenglishkids.britishcouncil.org/fun-games", ["Inglés", "Niños"]),
  r("British Council LearnEnglish Teens", "Idiomas", "Juegos y práctica de inglés para adolescentes.", "https://learnenglishteens.britishcouncil.org/study-break/games", ["Inglés", "Jóvenes"]),
  r("ESL Games Plus", "Idiomas", "Juegos interactivos de vocabulario y gramática inglesa.", "https://www.eslgamesplus.com/", ["Inglés", "ESL"]),
  r("EnglishClub Games", "Idiomas", "Juegos de pronunciación, vocabulario y gramática.", "https://www.englishclub.com/esl-games/", ["Inglés", "Juegos"]),
  r("MES Games", "Idiomas", "Actividades de vocabulario inglés con audio e imágenes.", "https://www.mes-games.com/", ["Inglés", "Vocabulario"]),
  r("Ba Ba Dum", "Idiomas", "Juego visual y auditivo de vocabulario en múltiples idiomas.", "https://babadum.com/", ["Vocabulario", "Audio"]),
  r("LanguageGuide", "Idiomas", "Vocabulario visual con pronunciación en varios idiomas.", "https://www.languageguide.org/", ["Pronunciación", "Visual"]),
  r("OnlineFreeSpanish", "Idiomas", "Vocabulario español con juegos y audio nativo.", "https://www.onlinefreespanish.com/", ["Español", "Audio"]),
  r("Spanish-Games.net", "Idiomas", "Lecciones, pruebas y catorce modalidades de juego.", "https://www.spanish-games.net/", ["Español", "Juegos"]),
  r("Let's Speak Spanish Games", "Idiomas", "Gramática y vocabulario organizados por niveles.", "https://letsspeakspanish.com/free-spanish-games/", ["Español", "Gramática"]),
  r("PandaTree Spanish", "Idiomas", "Colores, números, animales, clima y alimentos.", "https://www.pandatree.com/games/spanish", ["Español", "Niños"]),
  r("German-Games.net", "Idiomas", "Más de cien temas, catorce juegos y ninguna inscripción.", "https://www.german-games.net/", ["Alemán", "Juegos"]),
  r("Learn German With Games", "Idiomas", "Vocabulario, género, verbos y gramática A1–B1.", "https://www.learngermanwithgames.com/", ["Alemán", "Gramática"]),
  r("Conjuguemos", "Idiomas", "Conjugación y juegos en nueve idiomas; permite practicar sin cuenta.", "https://conjuguemos.com/", ["Verbos", "Idiomas"], "opcional"),
  r("LingoHut", "Idiomas", "Lecciones y juegos en más de sesenta idiomas sin login.", "https://www.lingohut.com/en", ["Idiomas", "Audio"]),
  r("GamesForLanguage", "Idiomas", "Juegos rápidos de español, francés, inglés, alemán e italiano.", "https://www.gamesforlanguage.com/", ["Idiomas", "Juegos"]),
  r("HelpfulGames German", "Idiomas", "Juegos escolares de vocabulario y gramática alemana.", "https://www.helpfulgames.com/subjects/german/", ["Alemán", "Escuela"]),
  r("Calico Spanish Games", "Idiomas", "Juegos gratuitos de vocabulario español para niños.", "https://calicospanish.com/learn-spanish-online-games/", ["Español", "Niños"]),

  // Finanzas y economía
  r("NGPF Arcade", "Finanzas", "Colección de juegos gratuitos sobre dinero y decisiones financieras.", "https://www.ngpf.org/arcade/", ["Finanzas", "Juegos"]),
  r("Build Your Stax", "Finanzas", "Comprime veinte años de decisiones de inversión en veinte minutos.", "https://buildyourstax.com/", ["Inversión", "Juego"]),
  r("Payback", "Finanzas", "Equilibra universidad, trabajo, bienestar y deuda estudiantil.", "https://www.timeforpayback.com/", ["Deuda", "Narrativo"]),
  r("SPENT", "Finanzas", "Toma decisiones difíciles con un presupuesto familiar limitado.", "https://playspent.org/", ["Presupuesto", "Decisiones"]),
  r("Financial Football", "Finanzas", "Responde preguntas financieras mientras juegas fútbol americano.", "https://www.practicalmoneyskills.com/en/play/financial_football.html", ["Dinero", "Deporte"]),
  r("The Uber Game", "Finanzas", "Simulación periodística sobre ingresos y decisiones de un conductor.", "https://ig.ft.com/uber-game/", ["Trabajo", "Economía"]),
  r("EconArena", "Finanzas", "Juegos de economía, mercados y toma de decisiones.", "https://www.econarena.com/", ["Economía", "Mercados"]),
  r("Econiverse", "Finanzas", "Actividades interactivas de economía para estudiantes.", "https://www.econiverse.org/", ["Economía", "Educativo"]),
  r("Intertwined Finance", "Finanzas", "Simulaciones de finanzas personales y decisiones económicas.", "https://www.intertwinedfinance.com/", ["Finanzas", "Simulación"]),
  r("The Fiscal Ship", "Finanzas", "Construye un presupuesto y controla la deuda pública.", "https://fiscalship.org/", ["Presupuesto", "Gobierno"]),
  r("Cleveland Fed Games", "Finanzas", "Trueque, presupuestos, ahorro e historia bancaria.", "https://www.clevelandfed.org/financial-literacy-resources", ["Ahorro", "Economía"]),
  r("ProjectionLab", "Finanzas", "Modela patrimonio, metas, jubilación y futuros financieros.", "https://projectionlab.com/", ["Planificación", "Escenarios"], "mixto"),
  r("FI Calc", "Finanzas", "Prueba estrategias de jubilación contra datos históricos.", "https://ficalc.app/", ["Retiro", "Histórico"]),
  r("Investopedia Simulator", "Finanzas", "Practica compraventa de acciones con dinero virtual.", "https://www.investopedia.com/simulator/", ["Bolsa", "Trading"], "mixto"),
  r("OptionStrat", "Finanzas", "Visualiza riesgo y beneficio de estrategias con opciones.", "https://optionstrat.com/", ["Opciones", "Riesgo"], "mixto"),
  r("CME Trading Simulator", "Finanzas", "Practica futuros y estrategias con datos de mercado.", "https://www.cmegroup.com/education/practice/about-the-trading-simulator", ["Futuros", "Mercado"], "mixto"),

  // Geografía, historia y cultura
  r("World Geography Games", "Geografía e historia", "Países, capitales, banderas, ríos y continentes.", "https://world-geography-games.com/", ["Geografía", "Mapas"]),
  r("Lizard Point", "Geografía e historia", "Cuestionarios de mapas, países, capitales e historia.", "https://lizardpoint.com/", ["Mapas", "Quiz"]),
  r("Seterra", "Geografía e historia", "Juegos de mapas y geografía de todo el mundo.", "https://www.geoguessr.com/quiz/seterra", ["Mapas", "Países"], "opcional"),
  r("MapChart", "Geografía e historia", "Crea y colorea mapas políticos e históricos.", "https://www.mapchart.net/", ["Mapas", "Crear"]),
  r("Google Earth", "Geografía e historia", "Explora el planeta, ciudades, relieve y recorridos.", "https://earth.google.com/web/", ["Tierra", "3D"]),
  r("Google Arts & Culture", "Geografía e historia", "Museos, obras, sitios históricos y experiencias culturales.", "https://artsandculture.google.com/", ["Arte", "Historia"]),
  r("British Museum Collection", "Geografía e historia", "Explora objetos y periodos de la historia humana.", "https://www.britishmuseum.org/collection", ["Museo", "Historia"]),
  r("iCivics", "Geografía e historia", "Juegos sobre gobierno, democracia, leyes y ciudadanía.", "https://www.icivics.org/games", ["Ciudadanía", "Gobierno"]),
  r("Ducksters History Games", "Geografía e historia", "Historia y geografía mediante juegos y cuestionarios.", "https://www.ducksters.com/games/", ["Historia", "Niños"]),
  r("National Geographic Kids", "Geografía e historia", "Juegos y actividades de animales, ciencia y geografía.", "https://kids.nationalgeographic.com/games", ["Geografía", "Niños"]),
  r("City Guesser", "Geografía e historia", "Adivina ciudades mediante videos reales.", "https://virtualvacation.us/guess", ["Ciudades", "Video"]),
  r("Guess Where You Are", "Geografía e historia", "Alternativa gratuita e ilimitada para adivinar ubicaciones.", "https://guesswhereyouare.com/", ["Ubicaciones", "Street View"]),
  r("Worldle", "Geografía e historia", "Identifica países por su silueta.", "https://worldle.teuteuf.fr/", ["Países", "Diario"]),
  r("Globle", "Geografía e historia", "Encuentra el país secreto mediante pistas de distancia.", "https://globle-game.com/", ["Países", "Distancia"]),
  r("Travle", "Geografía e historia", "Construye una ruta entre países limítrofes.", "https://travle.earth/", ["Rutas", "Países"]),
  r("GeoGames", "Geografía e historia", "Países, capitales, banderas, formas y mapas.", "https://geogames.io/", ["Mapas", "Banderas"]),
  r("JetPunk", "Geografía e historia", "Miles de cuestionarios públicos de geografía y cultura.", "https://www.jetpunk.com/", ["Quiz", "Cultura"], "opcional"),
  r("PurposeGames", "Geografía e historia", "Mapas, anatomía, ciencias e historia creados por la comunidad.", "https://www.purposegames.com/", ["Quiz", "Comunidad"], "opcional"),
  r("MapCrunch", "Geografía e historia", "Exploración aleatoria de lugares mediante Street View.", "https://www.mapcrunch.com/", ["Street View", "Explorar"]),
  r("Trivia Plaza", "Geografía e historia", "Cuestionarios de geografía, historia, ciencia, música y cine.", "https://www.triviaplaza.com/", ["Trivia", "Cultura"]),
  r("Flagle", "Geografía e historia", "Identifica una bandera mediante fragmentos.", "https://www.flagle.io/", ["Banderas", "Diario"]),
  r("Sporcle", "Geografía e historia", "Cuestionarios de cultura general, mapas, historia y ciencia.", "https://www.sporcle.com/", ["Quiz", "Trivia"], "opcional"),
  r("Hide and Seek World", "Geografía e historia", "Escondite multijugador utilizando ubicaciones del mundo.", "https://hideandseek.world/", ["Multijugador", "Mapa"], "opcional"),

  // Sociedad y ciudadanía
  r("Parable of the Polygons", "Sociedad y ciudadanía", "Simulación de segregación producida por pequeños sesgos.", "https://ncase.me/polygons/", ["Sesgo", "Sociedad"]),
  r("The Evolution of Trust", "Sociedad y ciudadanía", "Cooperación, engaño y teoría de juegos.", "https://ncase.me/trust/", ["Confianza", "Decisiones"]),
  r("Sabiduría o locura de las masas", "Sociedad y ciudadanía", "Redes sociales, contagio y comportamiento colectivo.", "https://ncase.me/crowds/es.html", ["Redes", "Sociedad"]),
  r("LOOPY", "Sociedad y ciudadanía", "Crea simulaciones mediante ciclos de causa y efecto.", "https://ncase.me/loopy/", ["Sistemas", "Causalidad"]),
  r("To Build a Better Ballot", "Sociedad y ciudadanía", "Compara sistemas electorales de manera interactiva.", "https://ncase.me/ballot/", ["Elecciones", "Gobierno"]),
  r("We Become What We Behold", "Sociedad y ciudadanía", "Simulación breve sobre medios y ciclos sociales.", "https://ncase.me/wbwwb/", ["Medios", "Sociedad"]),
  r("Bill of Rights Institute Games", "Sociedad y ciudadanía", "Federalismo, Congreso, burocracia y derechos civiles.", "https://billofrightsinstitute.org/games/", ["Gobierno", "Derechos"]),
  r("HelpfulGames Civics", "Sociedad y ciudadanía", "Juegos escolares sobre civismo y ciudadanía.", "https://www.helpfulgames.com/subjects/civics/", ["Civismo", "Escuela"]),
  r("Journey 2050", "Agricultura", "Gestiona agricultura, agua, economía y seguridad alimentaria.", "https://www.journey2050.com/2050-games/", ["Agricultura", "Futuro"]),

  // Arte, música y creación
  r("Chrome Music Lab", "Arte y música", "Experimentos musicales de ritmo, armonía, ondas y melodía.", "https://musiclab.chromeexperiments.com/", ["Música", "Experimentos"]),
  r("Song Maker", "Arte y música", "Crea melodías y ritmos sobre una cuadrícula visual.", "https://musiclab.chromeexperiments.com/Song-Maker/", ["Música", "Componer"]),
  r("Kandinsky", "Arte y música", "Convierte dibujos y formas en sonidos.", "https://musiclab.chromeexperiments.com/Kandinsky/", ["Dibujo", "Sonido"]),
  r("Chrome Rhythm", "Arte y música", "Experimenta con patrones rítmicos y percusión.", "https://musiclab.chromeexperiments.com/Rhythm/", ["Ritmo", "Música"]),
  r("AutoDraw", "Arte y música", "Dibujo asistido que reconoce trazos y propone ilustraciones.", "https://www.autodraw.com/", ["Dibujo", "IA"]),
  r("Quick, Draw!", "Arte y música", "Reta a una red neuronal a reconocer tus dibujos.", "https://quickdraw.withgoogle.com/", ["Dibujo", "IA"]),
  r("Paint With Music", "Arte y música", "Transforma trazos, colores y paisajes en música.", "https://artsandculture.google.com/experiment/paint-with-music/YAGuJyDB-XbbWg", ["Pintura", "Música"]),
  r("Blob Opera", "Arte y música", "Compón armonías controlando cuatro voces animadas.", "https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw", ["Voz", "Música"]),
  r("Kleki", "Arte y música", "Editor de pintura y dibujo que funciona directamente en web.", "https://kleki.com/", ["Dibujo", "Pintura"]),
  r("Patatap", "Arte y música", "Crea animaciones y sonidos utilizando el teclado.", "https://patatap.com/", ["Sonido", "Animación"]),
  r("Sampulator", "Arte y música", "Secuenciador musical rápido controlado con el teclado.", "https://sampulator.com/", ["Ritmo", "Sampler"]),
  r("OpenDAW", "Arte y música", "Estudio musical completo sin registro ni suscripción.", "https://opendaw.org/en", ["DAW", "Producción"]),
  r("BeepBox", "Arte y música", "Composición musical y guardado mediante URL.", "https://www.beepbox.co/", ["Música", "Secuenciador"]),
  r("Musicca Instruments", "Arte y música", "Piano, guitarra, bajo, violín, batería y xilófono virtuales.", "https://www.musicca.com/instruments", ["Instrumentos", "Música"]),
  r("ButtonBass", "Arte y música", "Sintetizadores, cajas de ritmos y producción musical.", "https://www.buttonbass.com/", ["Beats", "Sintetizador"]),
  r("Piskel", "Arte y música", "Editor de sprites animados y pixel art.", "https://www.piskelapp.com/", ["Pixel art", "Animación"]),
  r("Silk", "Arte y música", "Dibujo generativo y simétrico en pantalla completa.", "https://weavesilk.com/", ["Generativo", "Dibujo"]),
  r("Photopea", "Arte y música", "Edición avanzada de imágenes directamente en el navegador.", "https://www.photopea.com/", ["Imagen", "Editor"]),
  r("Incredibox Web Demo", "Arte y música", "Crea mezclas musicales con personajes de beatbox.", "https://www.incredibox.com/demo/", ["Beatbox", "Demo"], "mixto"),
  r("JS Paint", "Arte y música", "Recreación moderna de Microsoft Paint.", "https://jspaint.app/", ["Dibujo", "Retro"]),
  r("Sketchpad", "Arte y música", "Dibujo, pintura, vectores y texto en el navegador.", "https://sketch.io/sketchpad/", ["Dibujo", "Vectores"]),
  r("SculptGL", "Arte y música", "Escultura 3D como arcilla virtual.", "https://stephaneginier.com/sculptgl/", ["Escultura", "3D"]),
  r("Blockbench Web", "Arte y música", "Modelos 3D, texturas y animaciones low-poly.", "https://web.blockbench.net/", ["Modelado", "3D"]),
  r("drumbit", "Arte y música", "Caja de ritmos y secuenciador en el navegador.", "https://drumbit.app/", ["Batería", "Ritmo"]),
  r("Virtual Drumming", "Arte y música", "Baterías virtuales y juegos de ritmo.", "https://www.virtualdrumming.com/drums/online-virtual-games/online-virtual-games-drums.html", ["Batería", "Juego"]),

  // Educativos infantiles
  r("PBS KIDS Games", "Educativos infantiles", "Juegos educativos de ciencia, lectura, creatividad y matemáticas.", "https://pbskids.org/games/", ["Niños", "Educativo"]),
  r("ABCya", "Educativos infantiles", "Juegos escolares por grado y área de aprendizaje.", "https://www.abcya.com/", ["Primaria", "Juegos"], "mixto"),
  r("Funbrain", "Educativos infantiles", "Juegos de matemáticas, lectura y resolución de problemas.", "https://www.funbrain.com/games", ["Niños", "Escuela"]),
  r("Toy Theater", "Educativos infantiles", "Manipulativos, juegos, arte y actividades para primaria.", "https://toytheater.com/", ["Primaria", "Creatividad"]),
  r("Starfall", "Educativos infantiles", "Lectura, fonética y matemáticas para primeros grados.", "https://www.starfall.com/h/", ["Lectura", "Primaria"], "mixto"),
  r("Sheppard Software", "Educativos infantiles", "Juegos de ciencia, geografía, animales y matemáticas.", "https://www.sheppardsoftware.com/", ["Niños", "Educativo"]),
  r("Smithsonian STEM Game Center", "Educativos infantiles", "Juegos y simulaciones STEM revisados por especialistas.", "https://ssec.si.edu/game-center", ["STEM", "Smithsonian"]),
  r("Science Museum Games", "Educativos infantiles", "Juegos científicos del Science Museum Group.", "https://www.sciencemuseum.org.uk/games-and-apps", ["Ciencia", "Museo"]),
  r("MERLOT Simulations", "Educativos infantiles", "Colección abierta de simulaciones y materiales educativos.", "https://www.merlot.org/merlot/materials.htm?category=2178", ["Educación", "Colección"], "mixto"),

  // Transporte y navegación
  r("GeoFS", "Transporte", "Simulador de vuelo mundial con terreno satelital y clima.", "https://www.geo-fs.com/geofs.php", ["Vuelo", "Mundo"]),
  r("Google Earth Flight Simulator", "Transporte", "Pilota sobre paisajes y ciudades de Google Earth.", "https://earth.google.com/web/", ["Vuelo", "3D"]),
  r("ATC-SIM", "Transporte", "Gestiona aproximaciones y despegues desde una torre de control.", "https://atc-sim.com/", ["Aviación", "Control"]),
  r("Slow Roads", "Transporte", "Conduce por carreteras procedurales con clima y paisajes infinitos.", "https://slowroads.io/", ["Conducción", "Procedural"]),
  r("Shipmap", "Transporte", "Observa el movimiento del comercio marítimo mundial.", "https://www.shipmap.org/", ["Barcos", "Datos"]),

  // Emergencias y riesgo
  r("Stop Disasters!", "Emergencias", "Diseña comunidades resistentes a tsunamis, incendios y terremotos.", "https://www.stopdisastersgame.org/", ["Desastres", "Estrategia"]),
  r("Solve the Outbreak", "Emergencias", "Investiga epidemias y toma decisiones como un detective del CDC.", "https://www.cdc.gov/digital-social-media-tools/mobile/applications/sto/sto-web.html", ["Epidemias", "CDC"]),
  r("Asteroid Launcher", "Emergencias", "Calcula cráter, onda expansiva, calor y víctimas de un impacto.", "https://neal.fun/asteroid-launcher/", ["Asteroides", "Mapa"]),
  r("Impact Earth", "Emergencias", "Calculadora científica de impactos de asteroides.", "https://www.purdue.edu/impactearth/", ["Impacto", "Ciencia"]),
  r("Down2Earth", "Emergencias", "Simulador de formación de cráteres disponible en español.", "https://down2earth.eu/impact_calculator/", ["Cráteres", "Español"]),
  r("Project IMPACT", "Emergencias", "Impactos y estrategias para desviar asteroides.", "https://www.asteroidstrike.earth/", ["Mitigación", "Asteroides"]),
  r("COVID-19 Simulator", "Emergencias", "Prueba cómo las interacciones y la prevención alteran un contagio.", "https://ncase.me/covid-19/", ["Salud", "Sistemas"]),

  // Inteligencia artificial y datos
  r("Teachable Machine", "IA y datos", "Entrena modelos de imágenes, sonidos y posturas sin escribir código.", "https://teachablemachine.withgoogle.com/", ["IA", "Modelos"]),
  r("Quick, Draw!", "IA y datos", "Dibuja objetos mientras una red neuronal intenta reconocerlos.", "https://quickdraw.withgoogle.com/", ["IA", "Dibujo"]),
  r("Experiments with Google: AI", "IA y datos", "Colección de experimentos interactivos con aprendizaje automático.", "https://experiments.withgoogle.com/collection/ai", ["IA", "Experimentos"]),
  r("LearningML", "IA y datos", "Crea modelos de clasificación y proyectos de IA desde el navegador.", "https://learningml.org/", ["Machine learning", "Educación"], "opcional"),
  r("Machine Learning for Kids", "IA y datos", "Entrena modelos y úsalos en proyectos con Scratch, Python o App Inventor.", "https://machinelearningforkids.co.uk/", ["IA", "Programación"], "opcional"),
  r("AI for Oceans", "IA y datos", "Entrena un clasificador para distinguir peces y residuos en el océano.", "https://studio.code.org/s/oceans/lessons/1/levels/1", ["IA", "Clasificación"]),
  r("Semantris", "IA y datos", "Juego de asociación de palabras impulsado por modelos de lenguaje.", "https://research.google.com/semantris/", ["Lenguaje", "Juego"]),
  r("R2D3: Machine Learning", "IA y datos", "Explicación visual de árboles de decisión y aprendizaje automático.", "https://www.r2d3.us/visual-intro-to-machine-learning-part-1/", ["Visual", "Árboles"]),
  r("CNN Explainer", "IA y datos", "Observa capa por capa cómo una red convolucional reconoce imágenes.", "https://poloclub.github.io/cnn-explainer/", ["Red neuronal", "Visual"]),
  r("GAN Lab", "IA y datos", "Entrena una red generativa y explora cómo aprende distribuciones.", "https://poloclub.github.io/ganlab/", ["GAN", "Red neuronal"]),
  r("TensorFlow Embedding Projector", "IA y datos", "Explora representaciones de datos de alta dimensión en 2D y 3D.", "https://projector.tensorflow.org/", ["Datos", "Vectores"]),
  r("Setosa Image Kernels", "IA y datos", "Experimenta con filtros y convoluciones aplicados a imágenes.", "https://setosa.io/ev/image-kernels/", ["Imágenes", "Convolución"]),
  r("Setosa PCA", "IA y datos", "Comprende visualmente la reducción de dimensiones mediante componentes principales.", "https://setosa.io/ev/principal-component-analysis/", ["PCA", "Estadística"]),
  r("RAWGraphs", "IA y datos", "Convierte datos tabulares en visualizaciones editables sin subirlos a un servidor.", "https://app.rawgraphs.io/", ["Visualización", "Privacidad"]),
  r("Voyant Tools", "IA y datos", "Analiza palabras, frecuencias y relaciones dentro de textos propios.", "https://voyant-tools.org/", ["Texto", "Análisis"]),
  r("Google Trends", "IA y datos", "Compara el interés de búsqueda por temas, lugares y periodos.", "https://trends.google.com/trends/", ["Tendencias", "Datos"]),
  r("Our World in Data Explorer", "IA y datos", "Compara indicadores globales mediante mapas y gráficos interactivos.", "https://ourworldindata.org/explorers", ["Datos", "Mundo"]),
  r("Datawrapper", "IA y datos", "Crea gráficos, mapas y tablas para comunicar datos.", "https://app.datawrapper.de/", ["Gráficos", "Mapas"], "opcional"),
  r("Flourish", "IA y datos", "Diseña visualizaciones y narrativas de datos interactivas.", "https://flourish.studio/", ["Datos", "Narrativa"], "opcional"),
  r("Kaggle Learn", "IA y datos", "Microcursos prácticos de Python, datos, SQL e inteligencia artificial.", "https://www.kaggle.com/learn", ["Datos", "Cursos"], "opcional"),
  r("Orange Data Mining", "IA y datos", "Construye flujos visuales para analizar datos y entrenar modelos.", "https://orangedatamining.com/", ["Datos", "No-code"], "mixto"),

  // Ciberseguridad
  r("Jigsaw Phishing Quiz", "Ciberseguridad", "Identifica señales de phishing en correos y páginas simuladas.", "https://phishingquiz.withgoogle.com/", ["Phishing", "Correo"]),
  r("Interland", "Ciberseguridad", "Aventuras sobre contraseñas, privacidad, engaños y comportamiento seguro.", "https://beinternetawesome.withgoogle.com/es-419_all/interland", ["Seguridad", "Niños"]),
  r("CyberChef", "Ciberseguridad", "Analiza, codifica, cifra y transforma datos con operaciones encadenadas.", "https://gchq.github.io/CyberChef/", ["Criptografía", "Datos"]),
  r("picoCTF", "Ciberseguridad", "Retos de captura la bandera sobre web, criptografía, forense y reversing.", "https://picoctf.org/", ["CTF", "Retos"], "opcional"),
  r("CryptoHack", "Ciberseguridad", "Aprende criptografía resolviendo desafíos interactivos con código.", "https://cryptohack.org/", ["Criptografía", "Retos"], "opcional"),
  r("OverTheWire Bandit", "Ciberseguridad", "Practica Linux y seguridad conectándote a niveles progresivos.", "https://overthewire.org/wargames/bandit/", ["Linux", "Wargame"], "mixto"),
  r("PortSwigger Web Security Academy", "Ciberseguridad", "Laboratorios de vulnerabilidades web con explicaciones técnicas.", "https://portswigger.net/web-security", ["Web", "Laboratorios"], "opcional"),
  r("TryHackMe", "Ciberseguridad", "Salas guiadas y máquinas virtuales para aprender defensa y pruebas de seguridad.", "https://tryhackme.com/", ["Laboratorios", "Redes"], "mixto"),
  r("CyberDefenders", "Ciberseguridad", "Investiga incidentes y evidencia digital en laboratorios defensivos.", "https://cyberdefenders.org/blueteam-ctf-challenges/", ["Forense", "Blue team"], "opcional"),
  r("SANS Cyber Aces", "Ciberseguridad", "Fundamentos gratuitos de sistemas operativos, redes y administración segura.", "https://www.cyberaces.org/", ["Redes", "Fundamentos"]),
  r("OWASP Juice Shop", "Ciberseguridad", "Aplicación vulnerable intencionalmente para practicar seguridad web.", "https://owasp.org/www-project-juice-shop/", ["OWASP", "Web"], "mixto"),
  r("Data Detox Kit", "Ciberseguridad", "Actividades prácticas para mejorar privacidad, seguridad y bienestar digital.", "https://datadetoxkit.org/es/home", ["Privacidad", "Guías"]),
  r("Surveillance Self-Defense", "Ciberseguridad", "Guías de la EFF para proteger comunicaciones, dispositivos y cuentas.", "https://ssd.eff.org/es", ["Privacidad", "EFF"]),
  r("Have I Been Pwned", "Ciberseguridad", "Comprueba si una dirección aparece en filtraciones conocidas.", "https://haveibeenpwned.com/", ["Brechas", "Privacidad"]),
  r("How Secure Is My Password?", "Ciberseguridad", "Estima de forma educativa la resistencia de una contraseña de ejemplo.", "https://www.security.org/how-secure-is-my-password/", ["Contraseñas", "Prueba"]),
  r("NIST NICE Learning Resources", "Ciberseguridad", "Directorio oficial de juegos, cursos y laboratorios de seguridad digital.", "https://www.nist.gov/itl/applied-cybersecurity/nice/resources/online-learning-content", ["NIST", "Directorio"]),
  r("Mozilla Privacy Not Included", "Ciberseguridad", "Compara prácticas de privacidad y seguridad de productos conectados.", "https://foundation.mozilla.org/en/privacynotincluded/", ["Privacidad", "Evaluación"]),
  r("Internet Society Encryption", "Ciberseguridad", "Recursos visuales para comprender cifrado y comunicaciones seguras.", "https://www.internetsociety.org/issues/encryption/", ["Cifrado", "Internet"]),

  // Agricultura
  r("My American Farm", "Agricultura", "Juegos sobre cultivos, ganadería, alimentos, ciencia y economía rural.", "https://www.myamericanfarm.org/games/", ["Granja", "Juegos"]),
  r("USDA Web Soil Survey", "Agricultura", "Consulta mapas y propiedades oficiales de suelos para planificación agrícola.", "https://websoilsurvey.nrcs.usda.gov/app/", ["Suelos", "USDA"]),
  r("SoilWeb", "Agricultura", "Explora perfiles y datos de suelos sobre un mapa interactivo.", "https://casoilresource.lawr.ucdavis.edu/gmap/", ["Suelos", "Mapas"]),
  r("FAO Crop Calendar", "Agricultura", "Consulta épocas de siembra y cosecha de cultivos por país.", "https://cropcalendar.apps.fao.org/", ["Cultivos", "Calendario"]),
  r("FAO WaPOR", "Agricultura", "Analiza productividad del agua y agricultura mediante datos satelitales.", "https://wapor.apps.fao.org/home/WAPOR_3/1", ["Riego", "Satélite"]),
  r("FAO Hand-in-Hand Geospatial Platform", "Agricultura", "Combina mapas agrícolas, ambientales y socioeconómicos mundiales.", "https://data.apps.fao.org/", ["FAO", "Datos"]),
  r("FAO GAEZ Data Portal", "Agricultura", "Evalúa aptitud agroecológica, cultivos, clima y rendimiento potencial.", "https://gaez.fao.org/", ["Cultivos", "Clima"]),
  r("NASA Harvest Crop Monitor", "Agricultura", "Sigue condiciones y producción de cultivos mediante observación terrestre.", "https://cropmonitor.org/", ["NASA", "Cultivos"]),
  r("USDA CropScape", "Agricultura", "Visualiza cobertura y tipos de cultivos en mapas agrícolas.", "https://nassgeodata.gmu.edu/CropScape/", ["Cultivos", "Mapa"]),
  r("Global Yield Gap Atlas", "Agricultura", "Compara rendimientos actuales y potenciales de los principales cultivos.", "https://www.yieldgap.org/gygaviewer/index.html", ["Rendimiento", "Datos"]),
  r("AquaCrop", "Agricultura", "Simula la respuesta del rendimiento de cultivos al agua disponible.", "https://www.fao.org/aquacrop/en/", ["Riego", "Cultivos"], "mixto"),
  r("CROPWAT", "Agricultura", "Calcula necesidades de agua y programas de riego para diferentes cultivos.", "https://www.fao.org/land-water/databases-and-software/cropwat/en/", ["Riego", "FAO"], "mixto"),
  r("Pl@ntNet", "Agricultura", "Identifica plantas a partir de fotografías y contribuciones científicas.", "https://identify.plantnet.org/es", ["Plantas", "Identificación"], "opcional"),
  r("PlantVillage", "Agricultura", "Recursos para reconocer enfermedades y problemas de cultivos.", "https://plantvillage.psu.edu/", ["Sanidad vegetal", "Cultivos"], "opcional"),
  r("FAO Soils Portal", "Agricultura", "Mapas, datos y materiales para comprender y conservar los suelos.", "https://www.fao.org/soils-portal/en/", ["Suelos", "FAO"]),
  r("AgroAtlas", "Agricultura", "Mapas de cultivos, plagas, enfermedades y factores agroclimáticos.", "https://agroatlas.ru/en/", ["Plagas", "Mapas"]),
  r("Irrigation Association Calculators", "Agricultura", "Calculadoras de caudal, precipitación, uniformidad y programación de riego.", "https://www.irrigation.org/IA/Resources/Tools-Calculators/IA/Resources/Tools-Calculators.aspx", ["Riego", "Cálculo"]),
  r("Agriculture in the Classroom Matrix", "Agricultura", "Actividades y juegos educativos sobre agricultura y alimentos.", "https://agclassroom.org/matrix/", ["Educación", "Juegos"]),
  r("iNaturalist", "Agricultura", "Registra e identifica especies útiles para biodiversidad y manejo de fincas.", "https://www.inaturalist.org/", ["Biodiversidad", "Ciencia"], "opcional"),

  // Sostenibilidad
  r("Global Footprint Calculator", "Sostenibilidad", "Estima la huella ecológica personal y el día de sobregiro asociado.", "https://www.footprintcalculator.org/home/en", ["Huella", "Consumo"]),
  r("Water Footprint Calculator", "Sostenibilidad", "Calcula el agua utilizada directa e indirectamente por hábitos cotidianos.", "https://www.watercalculator.org/wfc2/", ["Agua", "Huella"]),
  r("CoolClimate Calculator", "Sostenibilidad", "Estima emisiones del hogar, transporte, alimentación, bienes y servicios.", "https://coolclimate.berkeley.edu/calculator", ["Carbono", "Hogar"]),
  r("Climate Action Simulation", "Sostenibilidad", "Juego de roles sobre políticas climáticas apoyado por el modelo En-ROADS.", "https://www.climateinteractive.org/climate-action-simulation/", ["Clima", "Roles"]),
  r("My2050", "Sostenibilidad", "Combina decisiones de energía y demanda para alcanzar objetivos de descarbonización.", "https://my2050.beis.gov.uk/", ["Energía", "Escenarios"]),
  r("Project Drawdown Explorer", "Sostenibilidad", "Explora soluciones climáticas por sector y su posible impacto.", "https://drawdown.org/solutions", ["Clima", "Soluciones"]),
  r("EPA Recycle City", "Sostenibilidad", "Recorre una ciudad y descubre acciones de reducción, reutilización y reciclaje.", "https://www3.epa.gov/recyclecity/", ["Reciclaje", "Ciudad"]),
  r("Electricity Maps", "Sostenibilidad", "Observa en tiempo real la intensidad de carbono de diferentes redes eléctricas.", "https://app.electricitymaps.com/map", ["Energía", "Datos en vivo"]),
  r("Global Carbon Atlas", "Sostenibilidad", "Visualiza emisiones, flujos de carbono y datos territoriales.", "https://globalcarbonatlas.org/", ["Carbono", "Mapas"]),
  r("PVGIS", "Sostenibilidad", "Calcula radiación y producción fotovoltaica para cualquier ubicación.", "https://re.jrc.ec.europa.eu/pvg_tools/en/", ["Solar", "Energía"]),
  r("Energy3D", "Sostenibilidad", "Diseña edificios y sistemas solares y analiza su rendimiento energético.", "https://energy.concord.org/energy3d/", ["Edificios", "Energía"], "mixto"),
  r("Go Goals!", "Sostenibilidad", "Juego educativo sobre los Objetivos de Desarrollo Sostenible.", "https://go-goals.org/", ["ODS", "Juego"], "mixto"),
  r("UN ActNow", "Sostenibilidad", "Acciones y retos cotidianos relacionados con clima y consumo responsable.", "https://www.un.org/en/actnow", ["ONU", "Acciones"]),
  r("Circular Classroom", "Sostenibilidad", "Actividades para comprender diseño circular, materiales y residuos.", "https://www.circularclassroom.com/", ["Circularidad", "Diseño"]),
  r("EcoChains", "Sostenibilidad", "Juego sobre redes alimentarias, biodiversidad y efectos del cambio climático.", "https://ecochains.umb.edu/", ["Ecosistemas", "Juego"], "mixto"),
  r("Climate Kids Games", "Sostenibilidad", "Juegos de NASA sobre energía, agua, carbono y clima.", "https://climatekids.nasa.gov/menu/play/", ["NASA", "Niños"]),
  r("Earth Overshoot Day", "Sostenibilidad", "Explora soluciones para retrasar el sobregiro ecológico mundial.", "https://overshoot.footprintnetwork.org/", ["Huella", "Planeta"]),

  // Emprendimiento
  r("Canvanizer", "Emprendimiento", "Construye modelos de negocio, propuestas de valor y otros lienzos visuales.", "https://canvanizer.com/new/business-model-canvas", ["Canvas", "Estrategia"], "opcional"),
  r("Strategyzer Business Model Canvas", "Emprendimiento", "Plantilla y guía del lienzo de modelo de negocio.", "https://www.strategyzer.com/library/the-business-model-canvas", ["Canvas", "Modelo"]),
  r("MOBI: Starting a Business", "Emprendimiento", "Curso abierto de la Universidad de Santa Clara para iniciar un negocio.", "https://www.scu.edu/mobi/business-courses/starting-a-business/", ["Negocios", "Curso"]),
  r("HP LIFE", "Emprendimiento", "Cursos gratuitos de negocio, mercadeo, finanzas y habilidades digitales.", "https://www.life-global.org/", ["Negocios", "Cursos"], "opcional"),
  r("SBA Learning Platform", "Emprendimiento", "Recursos oficiales para planear, lanzar, administrar y hacer crecer empresas.", "https://www.sba.gov/sba-learning-platform", ["Empresa", "Planificación"], "mixto"),
  r("SCORE Business Templates", "Emprendimiento", "Plantillas gratuitas de planes, proyecciones, mercadeo y operación.", "https://www.score.org/templates-resources", ["Plantillas", "Gestión"]),
  r("HubSpot Make My Persona", "Emprendimiento", "Construye perfiles de clientes para orientar producto y comunicación.", "https://www.hubspot.com/make-my-persona", ["Clientes", "Mercadeo"], "opcional"),
  r("Shopify Business Name Generator", "Emprendimiento", "Genera y explora nombres posibles para una marca o negocio.", "https://www.shopify.com/tools/business-name-generator", ["Marca", "Ideas"]),
  r("Google Market Finder", "Emprendimiento", "Explora mercados internacionales y oportunidades de expansión.", "https://marketfinder.thinkwithgoogle.com/intl/en/", ["Mercados", "Exportación"], "opcional"),
  r("Similarweb Website Analysis", "Emprendimiento", "Consulta estimaciones de tráfico y canales de sitios competidores.", "https://www.similarweb.com/website/", ["Competencia", "Mercado"], "mixto"),
  r("Break-even Calculator", "Emprendimiento", "Calcula el punto de equilibrio a partir de costos y precio de venta.", "https://www.calculator.net/break-even-calculator.html", ["Costos", "Finanzas"]),
  r("Profit Margin Calculator", "Emprendimiento", "Practica cálculo de margen, utilidad, costo e ingreso.", "https://www.omnicalculator.com/finance/margin", ["Margen", "Finanzas"]),
  r("Coffee Shop", "Emprendimiento", "Administra inventario, precio, receta y demanda de una cafetería virtual.", "https://www.coolmathgames.com/0-coffee-shop", ["Negocio", "Simulación"]),
  r("Lemonade Stand", "Emprendimiento", "Gestiona precio, inventario y decisiones diarias de un pequeño negocio.", "https://www.coolmathgames.com/0-lemonade-stand", ["Negocio", "Juego"]),
  r("Virtonomics", "Emprendimiento", "Simulación económica multijugador de empresas, producción y mercados.", "https://virtonomics.com/", ["Empresa", "Economía"], "opcional"),
  r("Sim Companies", "Emprendimiento", "Construye una compañía y compite en una economía virtual dirigida por jugadores.", "https://www.simcompanies.com/", ["Empresa", "Mercado"], "opcional"),
  r("Biz Kids Games", "Emprendimiento", "Juegos juveniles sobre negocios, dinero, riesgo y decisiones financieras.", "https://bizkids.com/games/", ["Negocios", "Jóvenes"]),

  // Psicología
  r("PsyToolkit Experiment Library", "Psicología", "Más de 50 experimentos cognitivos ejecutables en el navegador.", "https://www.psytoolkit.org/experiment-library/", ["Experimentos", "Cognición"]),
  r("PsyToolkit Stroop", "Psicología", "Experimenta la interferencia entre el significado de una palabra y su color.", "https://www.psytoolkit.org/experiment-library/stroop.html", ["Atención", "Stroop"]),
  r("PsyToolkit Simon Task", "Psicología", "Mide atención espacial, compatibilidad y tiempo de respuesta.", "https://www.psytoolkit.org/experiment-library/simon.html", ["Atención", "Reacción"]),
  r("PsyToolkit Go/No-Go", "Psicología", "Practica control inhibitorio y precisión frente a estímulos frecuentes.", "https://www.psytoolkit.org/experiment-library/go-no-go.html", ["Inhibición", "Impulsividad"]),
  r("Iowa Gambling Task", "Psicología", "Toma decisiones entre opciones con recompensas y pérdidas ocultas.", "https://www.psytoolkit.org/experiment-library/igt.html", ["Decisiones", "Riesgo"]),
  r("Human Benchmark Reaction Time", "Psicología", "Mide el tiempo de respuesta frente a un cambio visual.", "https://humanbenchmark.com/tests/reactiontime", ["Reacción", "Atención"]),
  r("Human Benchmark Sequence", "Psicología", "Recuerda secuencias visuales progresivamente más largas.", "https://humanbenchmark.com/tests/sequence", ["Memoria", "Secuencias"]),
  r("Human Benchmark Verbal Memory", "Psicología", "Reconoce palabras nuevas y repetidas para ejercitar memoria verbal.", "https://humanbenchmark.com/tests/verbal-memory", ["Memoria", "Lenguaje"]),
  r("Human Benchmark Number Memory", "Psicología", "Recuerda números de dificultad creciente.", "https://humanbenchmark.com/tests/number-memory", ["Memoria", "Números"]),
  r("Human Benchmark Visual Memory", "Psicología", "Memoriza la posición de cuadros dentro de una cuadrícula.", "https://humanbenchmark.com/tests/memory", ["Memoria", "Visual"]),
  r("Human Benchmark Chimp Test", "Psicología", "Ejercicio de memoria de trabajo y posición espacial.", "https://humanbenchmark.com/tests/chimp", ["Memoria", "Espacial"]),
  r("TestMyBrain", "Psicología", "Participa en pruebas breves de memoria, atención y coordinación.", "https://testmybrain.org/", ["Cognición", "Investigación"]),
  r("Greater Good Quizzes", "Psicología", "Cuestionarios de empatía, gratitud, relaciones y bienestar.", "https://greatergood.berkeley.edu/quizzes", ["Bienestar", "Berkeley"]),
  r("Self-Compassion Quiz", "Psicología", "Reflexiona sobre autocompasión mediante una escala académica.", "https://greatergood.berkeley.edu/quizzes/take_quiz/self_compassion", ["Autocompasión", "Emociones"]),
  r("Mindfulness Quiz", "Psicología", "Explora atención plena y respuesta ante el estrés cotidiano.", "https://greatergood.berkeley.edu/quizzes/take_quiz/mindfulness", ["Mindfulness", "Bienestar"]),
  r("Stress and Anxiety Quiz", "Psicología", "Cuestionario educativo sobre estrés y ansiedad, no diagnóstico.", "https://greatergood.berkeley.edu/quizzes/take_quiz/stress_and_anxiety", ["Estrés", "Educativo"]),
  r("Intellectual Humility Quiz", "Psicología", "Evalúa apertura mental y reconocimiento de los propios límites.", "https://greatergood.berkeley.edu/quizzes/take_quiz/intellectual_humility", ["Pensamiento", "Actitudes"]),
  r("Big Five IPIP", "Psicología", "Explora cinco dimensiones de personalidad mediante 50 preguntas.", "https://openpsychometrics.org/tests/IPIP-BFFM/", ["Personalidad", "Big Five"]),
  r("IPIP-NEO Extended", "Psicología", "Evaluación educativa detallada de Big Five y sus facetas.", "https://openpsychometrics.org/tests/IPIP-NEO-PI-R/", ["Personalidad", "Facetas"]),
  r("Holland RIASEC", "Psicología", "Relaciona intereses personales con tipos de actividades ocupacionales.", "https://openpsychometrics.org/tests/RIASEC/", ["Intereses", "Orientación"]),
  r("Open Extended Jungian Type", "Psicología", "Cuestionario recreativo de preferencias tipológicas.", "https://openpsychometrics.org/tests/OEJTS/", ["Personalidad", "Recreativo"]),
  r("16 Personality Factors", "Psicología", "Actividad educativa sobre factores y escalas de personalidad.", "https://openpsychometrics.org/tests/16PF.php", ["Personalidad", "Factores"]),
  r("Adventures with Anxiety", "Psicología", "Historia interactiva para comprender la función de la ansiedad.", "https://ncase.me/anxiety/", ["Ansiedad", "Narrativo"]),
  r("Neurotic Neurons", "Psicología", "Explicación jugable del aprendizaje asociativo y la ansiedad.", "https://ncase.me/neurons/", ["Aprendizaje", "Ansiedad"]),
  r("We Become What We Behold", "Psicología", "Juego sobre percepción social, medios y ciclos de conflicto.", "https://ncase.me/wbwwb/", ["Psicología social", "Medios"]),
  r("BrainFacts 3D Brain", "Psicología", "Modelo cerebral interactivo con estructuras y funciones.", "https://www.brainfacts.org/3d-brain", ["Cerebro", "3D"]),
  r("G2C 3D Brain", "Psicología", "Explora 29 estructuras cerebrales y sus funciones.", "https://www.g2conline.org/3dbrain/", ["Neurociencia", "3D"]),
  r("Neurotorium Brain Atlas", "Psicología", "Atlas 3D con regiones, vistas, etiquetas y referencias.", "https://neurotorium.org/tool/brain-atlas/", ["Cerebro", "Atlas"]),

  // Derecho
  r("Argument Wars", "Derecho", "Argumenta casos constitucionales reales ante una Corte Suprema simulada.", "https://ed.icivics.org/games/argument-wars", ["Litigación", "Constitucional"]),
  r("Do I Have a Right?", "Derecho", "Dirige un bufete y decide si los derechos de cada cliente fueron vulnerados.", "https://ed.icivics.org/games/do-i-have-right", ["Derechos", "Bufete"]),
  r("Court Quest", "Derecho", "Analiza conflictos y selecciona el tribunal competente para cada caso.", "https://ed.icivics.org/games/court-quest", ["Tribunales", "Competencia"]),
  r("LawCraft", "Derecho", "Propón, negocia y tramita un proyecto hasta convertirlo en ley.", "https://ed.icivics.org/games/lawcraft", ["Legislación", "Congreso"]),
  r("Branches of Power", "Derecho", "Representa los poderes Ejecutivo, Legislativo y Judicial.", "https://ed.icivics.org/games/branches-power", ["Estado", "Poderes"]),
  r("Race to Ratify", "Derecho", "Debate una ratificación constitucional y construye opinión pública.", "https://ed.icivics.org/games/race-to-ratify", ["Constitución", "Debate"]),
  r("Constitutional Compromise", "Derecho", "Negocia acuerdos constitucionales entre grupos con intereses diferentes.", "https://ed.icivics.org/games/constitutional-compromise", ["Constitución", "Negociación"]),
  r("Immigration Nation", "Derecho", "Resuelve casos educativos sobre ciudadanía y requisitos migratorios.", "https://ed.icivics.org/games/immigration-nation", ["Migración", "Ciudadanía"]),
  r("Virtual Courtroom Open University", "Derecho", "Explora una sala judicial inmersiva y conoce los roles de una audiencia.", "https://university.open.ac.uk/open-justice/virtual-courtroom", ["Juicio", "Sala virtual"]),
  r("US Courts Supreme Court Simulation", "Derecho", "Material oficial para representar argumentos orales ante una Corte Suprema.", "https://www.uscourts.gov/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/supreme-court-simulation", ["Argumentación", "Simulación"]),
  r("A Day in Court", "Derecho", "Juegos y actividades sobre audiencias, abogados y funcionamiento judicial.", "https://www.courts.michigan.gov/courts/supreme-court/learning-center/educational-resources/a-day-in-court-games/", ["Tribunales", "Juegos"]),
  r("Mock Trial and Civics", "Derecho", "Casos y lecciones para organizar juicios simulados escolares.", "https://njsbf.org/school-based-programs/mock-trial-civics-online-content/", ["Juicio", "Aula"]),
  r("LegalApp Colombia", "Derecho", "Encuentra rutas de justicia colombianas según el problema del ciudadano.", "https://www.minjusticia.gov.co/programas-co/LegalApp", ["Colombia", "Trámites"]),
  r("LegalApp Derecho de Petición", "Derecho", "Ruta práctica para comprender peticiones, quejas y reclamos.", "https://www.minjusticia.gov.co/programas-co/LegalApp/Paginas/Derecho-de-petici%C3%B3n-Queja-o-Reclamo.aspx", ["Colombia", "Petición"]),
  r("Consultorios Jurídicos Virtuales", "Derecho", "Directorio colombiano de universidades que prestan orientación jurídica.", "https://www.minjusticia.gov.co/programas-co/LegalApp/Paginas/Consultorios-juridicos-virtuales.aspx", ["Colombia", "Orientación"]),
  r("Glosario LegalApp", "Derecho", "Definiciones sencillas de conceptos y procedimientos jurídicos.", "https://www.minjusticia.gov.co/programas-co/LegalApp/Paginas/glosario-legalapp.aspx", ["Glosario", "Colombia"]),
  r("SUIN-Juriscol", "Derecho", "Consulta leyes, decretos, jurisprudencia y normativa colombiana.", "https://www.suin-juriscol.gov.co/index.html", ["Normas", "Colombia"]),
  r("Buscador de Normas Colombianas", "Derecho", "Busca normas por tipo, número, año o palabras clave.", "https://www.suin-juriscol.gov.co/legislacion/normatividad.html", ["Legislación", "Buscador"]),
  r("Constitución Política de Colombia", "Derecho", "Consulta artículos constitucionales y concordancias jurisprudenciales.", "https://www.secretariasenado.gov.co/senado/basedoc/constitucion_politica_1991.html", ["Constitución", "Colombia"]),
  r("Legal Information Institute", "Derecho", "Enciclopedia y base pública de legislación y jurisprudencia estadounidense.", "https://www.law.cornell.edu/", ["Investigación", "Cornell"]),
  r("Free Legal Research Sites", "Derecho", "Directorio universitario de bases jurídicas gratuitas.", "https://www.law.gmu.edu/library/freelegalresearch", ["Investigación", "Directorio"]),
  r("European e-Justice Portal", "Derecho", "Información sobre sistemas judiciales y procedimientos de la Unión Europea.", "https://e-justice.europa.eu/", ["Europa", "Justicia"]),
  r("EUR-Lex", "Derecho", "Legislación, tratados y jurisprudencia de la Unión Europea.", "https://eur-lex.europa.eu/", ["Europa", "Legislación"]),
  r("Ludoteca Jurídica", "Derecho", "Propuestas y recursos para aprender Derecho mediante juegos.", "https://ludotecajuridica.es/", ["Juegos", "Aprendizaje"]),
  r("Juegos Jurídicos UNED", "Derecho", "Contenidos lúdicos relacionados con Filosofía del Derecho.", "https://canal.uned.es/video/5a6f29b5b1111fd35f8b46ed", ["Filosofía", "UNED"]),

  // Comunicación
  r("Bad News", "Comunicación", "Adopta el papel de creador de desinformación para reconocer sus técnicas.", "https://www.getbadnews.com/", ["Desinformación", "Medios"]),
  r("Bad News Junior", "Comunicación", "Versión juvenil del juego para reconocer tácticas de noticias falsas.", "https://www.getbadnewsjunior.com/", ["Noticias", "Jóvenes"]),
  r("Harmony Square", "Comunicación", "Juego sobre manipulación política, polarización y difusión de información falsa.", "https://www.harmonysquare.game/", ["Desinformación", "Democracia"]),
  r("Go Viral!", "Comunicación", "Aprende a detectar manipulación y desinformación relacionada con salud.", "https://www.goviralgame.com/en", ["Desinformación", "Salud"]),
  r("BBC iReporter", "Comunicación", "Trabaja como periodista y equilibra precisión, impacto y velocidad.", "https://www.bbc.co.uk/news/resources/idt-8760dd58-84f9-4c98-ade2-590562670096", ["Periodismo", "Noticias"]),
  r("NewsFeed Defenders", "Comunicación", "Evalúa publicaciones y administra una red social informativa confiable.", "https://ed.icivics.org/games/newsfeed-defenders", ["Noticias", "Fuentes"]),
  r("Factitious", "Comunicación", "Decide si diferentes historias periodísticas son reales o inventadas.", "https://factitious.augamestudio.com/", ["Noticias", "Verificación"]),
  r("Fakey", "Comunicación", "Practica qué compartir, verificar o marcar dentro de una red social simulada.", "https://fakey.iuni.iu.edu/", ["Redes sociales", "Verificación"]),
  r("Spot the Troll", "Comunicación", "Analiza perfiles para distinguir cuentas auténticas de trolls profesionales.", "https://spotthetroll.org/", ["Redes sociales", "Trolls"]),
  r("Fake It to Make It", "Comunicación", "Simula el negocio y los incentivos económicos de las noticias falsas.", "https://fakeittomakeitgame.com/", ["Desinformación", "Simulación"]),
  r("The Republia Times", "Comunicación", "Edita un periódico y decide titulares bajo presión política.", "https://dukope.com/trt/play.html", ["Periodismo", "Edición"]),
  r("Which Face Is Real?", "Comunicación", "Intenta distinguir rostros reales de imágenes generadas por IA.", "https://www.whichfaceisreal.com/", ["IA", "Verificación"]),
  r("Google Fact Check Explorer", "Comunicación", "Busca verificaciones publicadas sobre afirmaciones y noticias.", "https://toolbox.google.com/factcheck/explorer", ["Fact-checking", "Buscador"]),
  r("Hemingway Editor", "Comunicación", "Revisa legibilidad, extensión de frases y claridad de un texto.", "https://hemingwayapp.com/", ["Escritura", "Claridad"], "mixto"),
  r("LanguageTool", "Comunicación", "Comprueba ortografía, gramática y estilo en varios idiomas.", "https://languagetool.org/", ["Escritura", "Gramática"], "mixto"),
  r("DeepL Write", "Comunicación", "Reformula textos y compara alternativas de redacción y tono.", "https://www.deepl.com/write", ["Redacción", "Estilo"]),
  r("Speechnotes", "Comunicación", "Practica dictado y convierte voz en texto desde el navegador.", "https://speechnotes.co/", ["Voz", "Dictado"]),
  r("Vocaroo", "Comunicación", "Graba y escucha intervenciones orales sin instalar software.", "https://vocaroo.com/", ["Voz", "Grabación"]),
  r("CuePrompter", "Comunicación", "Teleprónter en línea para practicar presentaciones y discursos.", "https://cueprompter.com/", ["Oratoria", "Presentaciones"]),
  r("Monkeytype", "Comunicación", "Practica velocidad, precisión y ritmo de escritura.", "https://monkeytype.com/", ["Escritura", "Velocidad"], "opcional"),
  r("Twine", "Comunicación", "Construye historias interactivas con decisiones y ramificaciones.", "https://twinery.org/2/", ["Narrativa", "Interactivo"]),
  r("Photopea", "Comunicación", "Edita imágenes y piezas de comunicación visual en el navegador.", "https://www.photopea.com/", ["Imagen", "Diseño"]),
  r("Audacity", "Comunicación", "Graba y edita voz, entrevistas, pódcast y paisajes sonoros.", "https://www.audacityteam.org/", ["Audio", "Pódcast"], "mixto"),
  r("Purdue OWL", "Comunicación", "Guías abiertas de escritura, citación, argumentación y comunicación profesional.", "https://owl.purdue.edu/owl/", ["Escritura", "Guías"]),
  r("Communication Games", "Comunicación", "Actividades grupales de escucha, claridad, asertividad y comunicación no verbal.", "https://futurumcareers.com/ten-simple-games-to-improve-your-communication-skills", ["Habilidades", "Actividades"]),

  // Oficios y formación técnica
  r("ElectraSim", "Oficios", "Diseña instalaciones con interruptores, luminarias, motores, tomas y protecciones.", "https://electrasim.com/", ["Electricidad", "Instalaciones"]),
  r("Electrical Troubleshooting Simulator", "Oficios", "Diagnostica averías industriales usando diagramas y multímetro virtual.", "https://bin95.com/industrial/electrical-troubleshooting.htm", ["Electricidad", "Diagnóstico"]),
  r("Electude Simulator Challenge", "Oficios", "Resuelve fallas de un sistema electrónico de gestión del motor.", "https://simulator.electude.com/", ["Automotriz", "Diagnóstico"]),
  r("GCodeTutor CNC Simulator", "Oficios", "Escribe código G y visualiza el recorrido de mecanizado.", "https://gcodetutor.com/cnc-program-simulator.html", ["CNC", "Código G"]),
  r("CutViewer", "Oficios", "Simula trayectorias CNC en 3D y detecta errores antes del corte.", "https://cutviewer.com/", ["CNC", "3D"]),
  r("CNC Web Simulator", "Oficios", "Simula torno, fresadora e impresora 3D desde el navegador.", "https://filipecaixeta.github.io/cncwebsim/", ["CNC", "Código abierto"]),
  r("Horizon G-code Analyzer", "Oficios", "Analiza y verifica trayectorias de herramientas en tres dimensiones.", "https://horizon-gcode.pages.dev/", ["CNC", "Verificación"]),
  r("NCViewer", "Oficios", "Visualiza código G y movimientos programados de una máquina CNC.", "https://ncviewer.com/", ["CNC", "Visualizador"]),
  r("Ladder Challenge", "Oficios", "Selecciona, coloca y utiliza correctamente una escalera en una obra.", "https://www.worksafebc.com/resources/health-safety/interactive-tools/ladder-challenge-game?lang=en", ["Construcción", "Seguridad"]),
  r("OSHA Hazard Identification", "Oficios", "Identifica peligros en escenarios de construcción y manufactura.", "https://www.osha.gov/hazfinder", ["Seguridad", "Riesgos"], "mixto"),
  r("What's Wrong with This Photo?", "Oficios", "Detecta riesgos en cocinas, obras, almacenes y montacargas.", "https://www.worksafebc.com/en/about-us/news-events/worksafe-magazine/whats-wrong-with-this-photo", ["Seguridad", "Observación"]),
  r("Workplace Rights and Responsibilities", "Oficios", "Libro interactivo sobre responsabilidades de trabajadores y empleadores.", "https://www.worksafebc.com/en/health-safety/create-manage/rights-responsibilities", ["Trabajo", "Seguridad"]),
  r("Heat Stress Screening Tool", "Oficios", "Evalúa condiciones que pueden producir estrés térmico en el trabajo.", "https://www.worksafebc.com/en/health-safety/hazards-exposures/heat-stress", ["Calor", "Prevención"]),
  r("Path to Pro", "Oficios", "Formación básica en construcción, electricidad, climatización, fontanería y pintura.", "https://www.pathtopro.com/free-training/", ["Construcción", "Cursos"], "opcional"),
  r("Theme Park Kitchen", "Oficios", "Practica lavado, cocción, temperaturas y prevención de contaminación cruzada.", "https://themeparkkitchen.com/", ["Cocina", "Seguridad alimentaria"]),
  r("Potluck Panic", "Oficios", "Juego de cartas sobre producción y manipulación segura de alimentos.", "https://foodsafety.osu.edu/children/food-safety-games", ["Alimentos", "Juego"]),
  r("Crazy Kitchen", "Oficios", "Localiza peligros y malas prácticas dentro de una cocina interactiva.", "https://www.foodstandards.gov.scot/education-resources/crazy-kitchen", ["Cocina", "Riesgos"]),
  r("Food Safety Activities", "Oficios", "Juegos sobre limpiar, separar, cocinar y enfriar alimentos.", "https://healthcanadaexperiences.ca/programs/food-safety/activities/", ["Cocina", "Higiene"]),
  r("Fight BAC Games", "Oficios", "Actividades para prevenir enfermedades transmitidas por alimentos.", "https://fightbac.org/kidsfoodsafety/kids-games-and-activities/", ["Alimentos", "Prevención"]),
  r("Car Mechanic Training", "Oficios", "Curso introductorio sobre componentes y mantenimiento de vehículos.", "https://alison.com/course/car-mechanic-training", ["Automotriz", "Curso"], "opcional"),
  r("DENSO Technic", "Oficios", "Cursos y evaluaciones técnicas para mecánicos y talleres.", "https://www.denso-technic.com/", ["Automotriz", "Certificados"], "opcional"),
  r("WorkSafeBC Student Resources", "Oficios", "Cuestionarios y materiales para trabajadores jóvenes o principiantes.", "https://www.worksafebc.com/en/health-safety/education-training-certification/young-new-worker/student-worksafe/student-resources", ["Seguridad", "Trabajo"]),

  // Arquitectura, diseño y urbanismo
  r("3D House Planner", "Arquitectura", "Diseña casas y apartamentos mediante planos y recorridos 3D.", "https://www.3dhouseplanner.com/", ["Vivienda", "3D"]),
  r("Remplanner", "Arquitectura", "Dibuja plantas arquitectónicas bidimensionales con medidas.", "https://remplanner.com/planner/", ["Planos", "2D"], "opcional"),
  r("Planner 5D", "Arquitectura", "Crea planos, amuebla espacios y realiza recorridos tridimensionales.", "https://planner5d.com/use/free-floor-plan-creator", ["Planos", "Interiores"], "opcional"),
  r("Floorplanner", "Arquitectura", "Diseña plantas 2D y visualizaciones 3D de espacios interiores.", "https://floorplanner.com/", ["Planos", "3D"], "opcional"),
  r("Arcadium 3D", "Arquitectura", "Diseña viviendas, oficinas, habitaciones y jardines.", "https://arcadium3d.com/", ["Vivienda", "Interiores"], "opcional"),
  r("Sweet Home 3D Online", "Arquitectura", "Dibuja una vivienda, coloca muebles y recórrela en 3D.", "https://www.sweethome3d.com/SweetHome3DJSOnline.jsp", ["Planos", "Muebles"]),
  r("Roomstyler 3D Planner", "Arquitectura", "Experimenta con distribución, mobiliario y acabados interiores.", "https://roomstyler.com/3dplanner", ["Interiores", "3D"], "opcional"),
  r("SketchUp Free", "Arquitectura", "Modela edificios, muebles y espacios urbanos desde el navegador.", "https://app.sketchup.com/", ["Modelado", "3D"], "opcional"),
  r("BlocksCAD", "Arquitectura", "Crea formas paramétricas tridimensionales mediante programación por bloques.", "https://www.blockscad3d.com/editor/", ["Modelado", "Bloques"], "opcional"),
  r("BIMx Model Viewer", "Arquitectura", "Explora modelos BIM compartidos y recorridos arquitectónicos.", "https://bimx.graphisoft.com/", ["BIM", "Visualizador"]),
  r("3D Sun-Path", "Arquitectura", "Estudia recorrido solar, duración del día y sombras según ubicación y fecha.", "https://andrewmarsh.com/apps/staging/sunpath3d.html", ["Sol", "Sombras"]),
  r("Shadowmap", "Arquitectura", "Visualiza sombras reales y potencial solar sobre edificios del mundo.", "https://shadowmap.org/", ["Sombras", "Mapa"]),
  r("SunCalc", "Arquitectura", "Consulta posición solar, orientación, amanecer y atardecer.", "https://www.suncalc.org/", ["Sol", "Orientación"]),
  r("SunEarthTools", "Arquitectura", "Calcula trayectoria solar, azimut, elevación y proyecciones.", "https://www.sunearthtools.com/dp/tools/pos_sun.php", ["Sol", "Cálculo"]),
  r("Dynamic Daylighting", "Arquitectura", "Modifica ventanas y protecciones para observar iluminación interior en tiempo real.", "https://andrewmarsh.com/software/daylight-box-web/", ["Iluminación", "Bioclimática"]),
  r("CBE Clima Tool", "Arquitectura", "Analiza temperatura, humedad, radiación, viento y confort de una localidad.", "https://clima.cbe.berkeley.edu/", ["Clima", "Confort"]),
  r("VELUX Daylight Visualizer", "Arquitectura", "Calcula iluminancia y distribución de luz natural en edificios.", "https://commercial.velux.com/inspiration/daylight-visualizer", ["Luz", "Simulación"], "mixto"),
  r("structureFIT MIT", "Arquitectura", "Explora configuraciones y comportamiento estructural de cerchas planas.", "https://digitalstructures.mit.edu/page/tools", ["Estructuras", "MIT"]),
  r("SkyCiv", "Arquitectura", "Modela y analiza vigas, cerchas y estructuras tridimensionales.", "https://skyciv.com/", ["Estructuras", "Ingeniería"], "opcional"),
  r("GIK Acoustic Room Designer", "Arquitectura", "Diseña una habitación y planea la ubicación del tratamiento acústico.", "https://www.gikacoustics.com/pages/acoustic-room-designer", ["Acústica", "Interiores"]),
  r("ATS Room Acoustics Analysis", "Arquitectura", "Estima características acústicas usando dimensiones y superficies.", "https://www.atsacoustics.com/page--Free-Online-Room-Acoustics-Analysis--ora.html", ["Acústica", "Cálculo"]),
  r("AMROC Room Mode Calculator", "Arquitectura", "Calcula modos, resonancias y distribución acústica de una habitación.", "https://amcoustics.com/tools/amroc", ["Acústica", "Frecuencias"]),
  r("Streetmix", "Arquitectura", "Diseña calles con andenes, árboles, ciclorrutas, buses y automóviles.", "https://streetmix.net/", ["Urbanismo", "Movilidad"]),
  r("StreetPlan", "Arquitectura", "Crea secciones viales y comprueba principios de calles completas.", "https://streetplan.net/", ["Urbanismo", "Calles"]),
  r("iPlan", "Arquitectura", "Resuelve problemas simulados de usos del suelo y planificación regional.", "https://www.i-plan.us/educators", ["Urbanismo", "Suelo"], "opcional"),
  r("BuildCity", "Arquitectura", "Construye una ciudad 3D con vías, servicios, zonas e impuestos.", "https://buildcity.io/", ["Ciudad", "Juego"], "opcional"),
  r("ThinkHazard", "Arquitectura", "Identifica amenazas naturales relevantes para una ubicación o proyecto.", "https://thinkhazard.org/", ["Riesgos", "Sitio"]),
  r("Global Flood Map", "Arquitectura", "Examina escenarios de inundación y aumento del nivel del mar.", "https://global-flood-map-for-planning.openearth.eu/", ["Inundación", "Planificación"]),
  r("GARDENA MyGarden", "Arquitectura", "Diseña jardines y planifica sistemas básicos de riego.", "https://my-garden.gardena.com/", ["Paisajismo", "Jardín"], "opcional"),

  // Juegos recreativos
  r("GamePix", "Juegos recreativos", "Portal de juegos HTML5 de acción, puzles, deportes y estrategia.", "https://www.gamepix.com/", ["HTML5", "Portal"]),
  r("CrazyGames", "Juegos recreativos", "Amplio catálogo de juegos gratuitos para navegador.", "https://www.crazygames.com/", ["Portal", "Juegos"], "opcional"),
  r("Addicting Games", "Juegos recreativos", "Juegos casuales, acción, estrategia y habilidad.", "https://www.addictinggames.com/", ["Casual", "Portal"]),
  r("Plays.org", "Juegos recreativos", "Miles de juegos HTML5 para computador y móvil.", "https://plays.org/", ["HTML5", "Portal"], "opcional"),
  r("Armor Games", "Juegos recreativos", "Aventuras, estrategia, acción y juegos independientes.", "https://armorgames.com/", ["Estrategia", "Portal"], "opcional"),
  r("Y8", "Juegos recreativos", "Gran catálogo de juegos de navegador por categorías.", "https://www.y8.com/", ["Portal", "Multijugador"], "opcional"),
  r("247 Games", "Juegos recreativos", "Solitario, sudoku, mahjong, cartas y puzles.", "https://www.247games.com/", ["Clásicos", "Puzles"]),
  r("itch.io Browser Games", "Juegos recreativos", "Juegos independientes gratuitos que se ejecutan en el navegador.", "https://itch.io/games/free/platform-web", ["Indie", "Web"], "opcional"),
  r("Game Jolt", "Juegos recreativos", "Juegos independientes y comunidades de creadores.", "https://gamejolt.com/games", ["Indie", "Comunidad"], "mixto"),
  r("Newgrounds Games", "Juegos recreativos", "Juegos independientes y experimentales publicados por la comunidad.", "https://www.newgrounds.com/games", ["Indie", "Comunidad"], "opcional"),
  r("Internet Archive DOS Games", "Juegos recreativos", "Clásicos de DOS emulados directamente en el navegador.", "https://archive.org/details/softwarelibrary_msdos_games", ["Retro", "Emulación"]),
  r("ClassicReload", "Juegos recreativos", "Juegos antiguos de DOS y Windows ejecutables en web.", "https://classicreload.com/", ["Retro", "Clásicos"]),
  r("Little Alchemy 2", "Juegos recreativos", "Combina elementos y descubre cientos de objetos nuevos.", "https://littlealchemy2.com/", ["Creativo", "Puzle"]),
  r("Lichess", "Juegos recreativos", "Ajedrez gratuito contra personas, amigos o computadora.", "https://lichess.org/", ["Ajedrez", "Estrategia"], "opcional"),
  r("TETR.IO", "Juegos recreativos", "Juego moderno de bloques con modos individual y multijugador.", "https://tetr.io/", ["Bloques", "Multijugador"], "opcional"),
  r("skribbl.io", "Juegos recreativos", "Dibujo y adivinanzas multijugador mediante salas privadas.", "https://skribbl.io/", ["Dibujo", "Multijugador"]),
  r("CardGames.io", "Juegos recreativos", "Cartas y juegos de mesa sin registro.", "https://cardgames.io/", ["Cartas", "Clásicos"]),
  r("FreeBoardGames.org", "Juegos recreativos", "Ajedrez, damas y juegos contra IA, locales o por enlace.", "https://www.freeboardgames.org/", ["Mesa", "Código abierto"]),
  r("BuddyBoardGames", "Juegos recreativos", "Partidas con amigos sin iniciar sesión ni descargar.", "https://buddyboardgames.com/", ["Mesa", "Amigos"]),
  r("Solitr", "Juegos recreativos", "Solitario gratuito sin registro.", "https://www.solitr.com/", ["Solitario", "Cartas"]),
  r("Friv", "Juegos recreativos", "Colección familiar sin descargas ni compras dentro del juego.", "https://www.friv.com/", ["Familia", "Portal"]),
  r("Playhop", "Juegos recreativos", "Portal con miles de juegos de navegador sin login.", "https://playhop.com/", ["Portal", "HTML5"]),
  r("The Jigsaw Puzzles", "Juegos recreativos", "Miles de rompecabezas gratuitos en línea.", "https://thejigsawpuzzles.com/", ["Rompecabezas", "Fotos"], "opcional"),
  r("Daily Jigsaw Puzzles", "Juegos recreativos", "Rompecabezas familiares sin descarga ni registro.", "https://www.dailyjigsawpuzzles.net/", ["Rompecabezas", "Diario"]),
  r("Jigsaw Explorer", "Juegos recreativos", "Rompecabezas, imágenes propias y modo multijugador.", "https://www.jigsawexplorer.com/", ["Rompecabezas", "Multijugador"]),
  r("A Dark Room", "Juegos recreativos", "Aventura minimalista de supervivencia y exploración.", "https://adarkroom.doublespeakgames.com/", ["Aventura", "Texto"]),
  r("Candy Box 2", "Juegos recreativos", "Aventura incremental con exploración y acertijos.", "https://candybox2.github.io/", ["Incremental", "Aventura"]),
  r("Universal Paperclips", "Juegos recreativos", "Simulación incremental de producción y automatización.", "https://www.decisionproblem.com/paperclips/index2.html", ["Incremental", "Estrategia"]),
  r("Townscaper Web", "Juegos recreativos", "Demostración gratuita para construir ciudades costeras.", "https://oskarstalberg.com/Townscaper/", ["Construcción", "Creativo"], "mixto"),
];

export const accessMeta: Record<Access, { label: string; short: string }> = {
  directo: { label: "Acceso directo, sin cuenta", short: "Sin cuenta" },
  opcional: { label: "Se puede probar sin cuenta; cuenta opcional para guardar", short: "Cuenta opcional" },
  mixto: { label: "Acceso gratuito limitado, descarga o cuenta en algunas funciones", short: "Acceso mixto" },
};

export const categories = Object.keys(categoryMeta) as Category[];
